### PR TITLE
Fix book content inversion on Kindle Cloud Reader

### PR DESCRIPTION
**Pull request by ThatChristianGuy**
read.amazon.com

### CODE REVIEW

**Review by Gusted — COMMENTED** [review]
Hm, why should the content be inverted? Doesn't that include images?

**Comment by dzaikos** [comment]
I just started using DarkReader and while I'm not the author of this PR, I can say that Kindle Cloud Reader now renders pages dynamically, on-demand, as images. This means normal CSS for changing fore- and background text don't affect the actual book content. Inverting images inside `#kindleReader_content` would produce the correct results.

It should be noted that this PR isn't valid anymore because since it was submitted further commits to this file now provide specific instructions for `read.amazon.com`, although the correct domain should be `read.amazon.*` since country-codes are a possibility with Kindle Cloud Reader.

**Comment by Gusted** [comment]
> I just started using DarkReader and while I'm not the author of this PR, I can say that Kindle Cloud Reader now renders pages dynamically, on-demand, as images. This means normal CSS for changing fore- and background text don't affect the actual book content. Inverting images inside `#kindleReader_content` would produce the correct results.
> 
> It should be noted that this PR isn't valid anymore because since it was submitted further commits to this file now provide specific instructions for `read.amazon.com`, although the correct domain should be `read.amazon.*` since country-codes are a possibility with Kindle Cloud Reader.

Thank you for testing out the PR, I will update it a bit and get it merged.

**Review by Gusted — APPROVED** [review]

**Comment by Gusted** [comment]
Superseeded by #7523

**Pull request closed without merging**
