### PR TITLE
Fx color

### PR DESCRIPTION
**Pull request by bershanskiy**

### CODE REVIEW

**Comment by MahdiNazemi** [comment]
Has a release timeline been established for the fix to be rolled out on AMO?

**Comment by bershanskiy** [comment]
Hi @MahdiNazemi we started release process and 4.9.64 is already up on CWS. If everything goes smooth, we will publish to AMO shortly. I expect AMO to have a new version early next week, or at the latest by the end of next week.

**Comment by bershanskiy** [comment]
Update: Dark Reader 4.9.64 is available on Firefox Add-ons (sometimes called AMO) since 26 June.

**Comment by MahdiNazemi** [comment]
Thank you! The extension has been working flawlessly so far.

**Pull request merged**
