### PR TITLE
Fix for google.*

### PR DESCRIPTION
**Pull request by Rakleed**
Exmaple: https://www.google.com/search?q=валдайский+национальный+парк

### CODE REVIEW

**Comment by Rakleed** [comment]
Updated rules appear after updating the extension, right? And how often is the extension updated?

**Comment by Gusted** [comment]
Every weeks I guess no definte answer to it.

**Comment by Gusted** [comment]
Couldn't find all CSS Selectors on the page.

**Comment by Rakleed** [comment]
> Couldn't find all CSS Selectors on the page.

<details>
<summary>Screenshots</summary>

screenshot-www-google-com-search-1591905399096

screenshot-www-google-com-search-1591905161412

screenshot-www-google-com-search-1591905549744

</details>

**Comment by Gusted** [comment]
LGTM

**Pull request merged**
