### PR TITLE
Added Discord to Dark Sites Config

### PR DESCRIPTION
**Pull request by OfficialCRUGG**
I've added Discord to the dark site theme config, as it already uses a dark theme and Darkreader just messes it up and makes it a thousand times worse

### CODE REVIEW

**Comment by alexanderby** [comment]
Sorry, every month somebody adds Discord into this list, and later somebody removes it from list because not all pages are dark. I'm going to fix it by letting ignoring dark list.

**Comment by OfficialCRUGG** [comment]
Could I ask where the hell discord is supossed to have non-dark pages?

**Comment by alexanderby** [comment]
For example here https://support.discordapp.com/hc/en-us/articles/218449248-Permissions-Lockout

**Comment by OfficialCRUGG** [comment]
Oh the Zendesk Page. Completely forgot about that one.

**Comment by alexanderby** [comment]
Sorry, your PR was duplicate of https://github.com/darkreader/darkreader/pull/1240/

**Pull request closed without merging**
