### PR TITLE
Invert Google apps, Github Education's, AWS's, The Verge's icon and math element on Wikipedia properly

### PR DESCRIPTION
**Pull request by Tansc161**
**Example Article: https://en.wikipedia.org/wiki/Megagon**
### Before
图片
图片
### After
图片
图片

### CODE REVIEW

**Comment by Tansc161** [comment]
## New commit: Invert Google Apps Icon properly on Google homepage
**Demo:** https://google.com

| Before | After |
| --- | --- |
| Before | After |
##### Note: I'm using `zh_CN` as the page language, tested on `en` too

**Comment by Tansc161** [comment]
## New commit: Fix logos on Github Education site
**Demo:** https://education.github.com/

|  Before  |  After  |
| ------- | ------- |
| Before1 | After1 |
| Before2 | After2 |

**Comment by Tansc161** [comment]
## New commit: Fix logos on Amazon AWS site
**Demo:** https://aws.amazon.com/free/
**Demo 2:** https://aws.amazon.com/

|  Before  |  After  |
| ------- | ------- |
| Before1 | After1 |
| Before2 | After2 |

*And many more...*

**Comment by Tansc161** [comment]
## New commit: Light up The Verge's logo
**Demo:** https://www.theverge.com/ and any of its news page

|  Before  |  After  |
| ------- | ------- |
| Before | After |

**Comment by alexanderby** [comment]
Thanks for the fixes. One note, it is better to submit one Pull Request per website.

**Pull request merged**
