### PR TITLE
Fix for iqiyi.com

### PR DESCRIPTION
**Pull request by felixonmars**
- Fix background of user info popup

### CODE REVIEW

**Review by Gusted — COMMENTED** [review]
"background of user info popup", hmm is this like a `div` acting as a background model? As in such case I don't think a INVERT should be used. Could you point me to where I can find this element?

**Comment by felixonmars** [comment]
> "background of user info popup", hmm is this like a `div` acting as a background model? As in such case I don't think a INVERT should be used. Could you point me to where I can find this element?

It is an <i> with a background-image, acting like a background. If I unset the background-image here, it will become transparent and makes the text unreadable.

It's shown at the top of the popup window when hovering over your avatar after login.

**Review by Gusted — APPROVED** [review]
All good then.

**Comment by felixonmars** [comment]
No fix:
DeepinRuudunkaappaus_valitse-alue_20210820213644

Unset background-image:
DeepinRuudunkaappaus_valitse-alue_20210820213659

Invert:
DeepinRuudunkaappaus_valitse-alue_20210820213713

**Pull request merged**
