### PR TITLE
messages.google.com is dark

### PR DESCRIPTION
**Pull request by Simsimpicpic**

### CODE REVIEW

**Comment by Gusted** [comment]
No it's not?

**Comment by Simsimpicpic** [comment]
Uhh, yeah : 
https://messages.google.com/ is not dark,
but https://messages.google.com/web/conversations is dark.

**Comment by Gusted** [comment]
`https://messages.google.com/ ` Is not equal to `https://messages.google.com/web/conversations`

**Comment by Gusted** [comment]
You had dark theme enabled.

**Comment by Simsimpicpic** [comment]
Uh, yeah sorry !

**Comment by Gusted** [comment]
No problems 🥂

**Pull request closed without merging**
