### PR TITLE
Update dynamic theme fix for `porkbun.com`

### PR DESCRIPTION
**Pull request by oberrich**
Properly invert sales chat pop-up

*(before)*

*(after)*

### CODE REVIEW

**Comment by oberrich** [comment]
I see there is a slight problem: The chat pop-up gets loaded in delayed. Is there some way to config dark-reader to be run again on DOM change or something?

**Comment by alexanderby** [comment]
What browser are you using? I don't see such white corners.

**Comment by oberrich** [comment]
> What browser are you using? I don't see such white corners.

Version 123.0.6312.113 (Official Build, ungoogled-chromium) (64-bit) and I have a fast connection through fiber optic cable.
Opening the site sometimes results in the image being white, if I disable and reenable it for porkbun *after* loading the site, it correctly inverts the image.

The chat widget is loaded through an iframe - possibly at a later point, maybe that causes the issue?

**Comment by oberrich** [comment]
Landed in 46af1fd67e2d9629d2926547a6e394effd542e67

**Pull request closed without merging**
