### PR TITLE
Fix to have dark PDFs.

### PR DESCRIPTION
**Pull request by Myshor**
Making as separate pull request as I don't know if we want to have it in Dynamic or not. ;)

### CODE REVIEW

**Comment by alexanderby** [comment]
Nice and simple solution. It looks like it didn't work before for Chrome. I will put this on hold, since some users don't want inverting PDFs. Currently I'm working on settings page redesign, and option for inverting PDFs will be added there.

**Comment by AndiLeni** [comment]
@alexanderby I did not know where to put this, but I think it fits here.
For inverting pdf files on firefox you can invert the ``.page`` class. This works very well. 
Could you consider adding this as well when you change this feature for chrome?

**Comment by gaurav-varshneya** [comment]
Nice! Was looking for this functionality. However, this fix doesn't work for PDF's that are downloaded to your computer then viewed in Chrome.

**Comment by alexanderby** [comment]
@gaurav-varshneya You have to go to chrome://extensions page, find Dark Reader and click "Enable access to file URLs".

@AndiLeni Unfortunately the scripts cannot be injected into PDF viewer in Firefox.

**Comment by Gusted** [comment]
Closed as of #2367 has been merged and will be released with darkreader V5

**Pull request closed without merging**
