### PR TITLE
Add mkbhd.com to dark-sites.config file

### PR DESCRIPTION
**Pull request by theofficial-thinktech**
Added a new website since its theme is dark by itself.

### CODE REVIEW

**Comment by theofficial-thinktech** [comment]
Am I supposed to do something else, to do the commit?
I am new to Git so any suggestions are appreciated.

**Comment by alexanderby** [comment]
Hi @theofficial-thinktech, thanks, no changes are needed. Sorry for the delay.

**Comment by theofficial-thinktech** [comment]
Thank you @alexanderby, it was my first PR so I was a bit confused.
It indeed does feel good to contribute even the tiniest bit, as it's these tiny drops that create the ocean!

**Comment by alexanderby** [comment]
Right, thanks. I will publish an update with your fixes soon.

**Pull request merged**
