### PR TITLE
octotree fixes

### PR DESCRIPTION
**Pull request by thenanyu**
there's a popular extension called Octotree, which provides a nice sidebar nav for github projects

### CODE REVIEW

**Comment by kbulygin** [comment]
May I ask why did you do that? The sidebar is light now even though the rest of each GitHub page is dark. I wish I could cancel the change without reverting to a custom version of Dark Reader.

**Comment by thenanyu** [comment]
Something seems inconsistent here, this is the result it produces for me
image

**Comment by kbulygin** [comment]
Here is my screenshot: screenshot from 2019-01-04 21-43-15

Before the time when this PR was merged, the sidebar was dark as in your screenshot. I use Chrome 71.0.3578.80 (Official Build) (64-bit), Dark Reader 4.7.4.

**Comment by kbulygin** [comment]
I've just found out that once the theme engine (on the tab "More" in the settings of Dark Reader) is changed from "Filter" to "Dynamic", the appearance matches your screenshot. But, well, the theme engine "Dynamic" is experimental and "Filter" is not according to description on the tab.

**Comment by thenanyu** [comment]
Ah I see, I was unaware that dynamic was experimental, I thought it was actually default. If the guidelines are that Filter is the blessed version, then maybe we should revert.

**Comment by alexanderby** [comment]
@kbulygin This message will be removed soon, Dynamic mode works stable.

There was another Pull Request regarding Octotree for Dynamic mode, I merged it yesterday https://github.com/darkreader/darkreader/pull/940

Feel free to undo wrong changes in new PR.

**Comment by kbulygin** [comment]
@thenanyu Sorry for the reverting!

**Pull request merged**
