### PR TITLE
fix: amazon images background color

### LINKED ISSUE #12569: [Broken Website] Using darkreader with amazon.fr leads to unreadable items
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Using darkreader with amazon.fr leads to unreadable items.

### Website Address

amazon.fr

### Steps To Reproduce

1. go to amazon.fr
2. read the webpage

Some items are black on black. They are unreadable.

### Screenshots

dark_reader_enabled

dark_reader_disabled

### Operating System

openSUSE Tumbleweed

### Web Browser name and version

Firefox 124.0.2

### Dark Reader version

4.9.81

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kantum**
Some images use the alpha channel as white, this PR fixes #12569

### CODE REVIEW

**Comment by Myshor** [comment]
@kantum Can you share exact URL which you used to make this fix?

Because I think I was already fixing something similar using this part of code which is even partially visible in the PR:
```
[class*="image-display"],
.a-image-container img,
[class*="imageContainer"] img {
    mix-blend-mode: unset !important;
}
```

this `imageContainer` repeating in CSS code is making me courious if this fix is really needed anymore. 😉

**Comment by kantum** [comment]
It was on amazon.fr/ and amazon.com/.

I experienced the problem yesterday, however I cannot reproduce the problem now.

I had selectors looking like this:
```css
[data-pf=DESKTOP] ._cDEzb_imgBC_1XEOV
```

It may have been an A/B test from Amazon, or another add-on doing strange stuff.

The selector `productImageContainer` was for small images appearing on top of the screen, recommendation or something, it doesn't match `imageContainer` because of the capital i.
```css
_cDEzb_productImageContainer_3uG0t
```

I will reset my config for amazon.* and let you know if I experience the problem again.

**Comment by kantum** [comment]
I accidentally switched to mobile and reproduced the result, so these are the problematic URLs:

https://www.amazon.fr/hz/mobile/mission
https://www.amazon.com/hz/mobile/mission

```css
class="a-section a-spacing-none a-text-center _cDEzb_productImageContainer_3uG0t"
```

image

```css
class="a-section a-spacing-small _cDEzb_container_46qRr
 
 _cDEzb_imgBC_1XEOV"
```
image

It may be related

**Comment by Myshor** [comment]
OK... I'll push a small change that will not put background to whole container but disable blendig picture with background for missing selectors inside that. That will merge old fix for other containers with this one. 😉

**Pull request merged**
