### PR TITLE
Fix labels and borders in ProtonMail Beta

### PR DESCRIPTION
**Pull request by fishstik**

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @fishstik!

What is trying to be achieved by this PR?

Regards,
Gusted

**Comment by fishstik** [comment]
Fixes coloring of labels and white borders for ProtonMail Beta.

**Comment by Gusted** [comment]
Somehow I'm getting a unkown error when I try to login into the beta of protan-mail. But I'm guessing dark reader is modifying the colors of those elements trough a Inline style?

**Comment by fishstik** [comment]
I'm not sure how Dark Reader is modifying these elements. The changes I added simply reinstate the original named colors that protonmail uses. I tried INVERT and IGNORE INLINE STYLE on them and it didn't change anything.

**Pull request merged**
