### PR TITLE
dark-sites.config: Add kompjuteras.com

### PR DESCRIPTION
**Pull request by zoranzoki21**
Same reason as for #2525

### CODE REVIEW

**Comment by Gusted** [comment]
Screenshot_20200516_161407_com brave browser
Not dark at first sight

**Comment by zoranzoki21** [comment]
Screenshot_20200516_174121_com android chrome

**Comment by Gusted** [comment]
Same behavior on an incognito tab?

**Comment by zoranzoki21** [comment]
> Same behavior on an incognito tab?

Yes

**Pull request closed without merging**
