### PR TITLE
Fix for github.com and github.*.com

### LINKED ISSUE #4182: [Broken Website] Github has grey colors
**Website**
https://github.com

**How to Reproduce**

Visit any repository.

**Expected behavior**

Before, GitHub was dark as it should, but I guess they changed some styles, so .. now things don't work as expected anymore.

**Actual behavior**
Everything is grey instead of black.

**Screenshots**

image

image

**System info:**

- OS: MacOS
- Browser: Firefox 82.0.3 (64-bit)
- Darkreader Version: 4.9.23

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by AndrewDaGuy**
To-Do: 
- ~~Fix "Home Page"~~

Changes:
- Inverted codespaces retina-burning-white images
- Inverted the *o c t o p r i n t e r*
- Inverted some things in Github Explore

Broken things:
- Codespaces "day to night" animation is broken (day has weird white thingys. i have no idea how to fix it)

Partially resolves #4182

### CODE REVIEW

**Comment by AndrewDaGuy** [comment]
> Huge mess, could be optimized, but that's another point.
> 
> So basically every image: Where can I find it.

So invert every image on the planet?

**Comment by Gusted** [comment]
> So invert every image on the planet?

I meant, for each of this image. Where do I find this image.

**Comment by AndrewDaGuy** [comment]
> > So invert every image on the planet?
> 
> I meant, for each of this image. Where do I find this image.

The github "homepage" (Logged out) and https://guthub.com/features/codespaces

**Review by Gusted — APPROVED** [review]
LGTM

**Pull request merged**
