### PR TITLE
Add option to automatically toggle dark mode on sunrise/sunset ( #72 )

### PR DESCRIPTION
**Pull request by Kimbatt**
Hi,
I added an option to automatically toggle dark mode on sunrise/sunset.  ( #72 )

You need to enter your approximate location (latitude and longitude) to use it. (the algorithm to calculate sunrise/sunset time is mostly taken from [here](https://gist.github.com/Tafkas/4742250) )

image

image

Also, I had to add auto-translated strings for the tests to pass.
This is my first pull request here, so suggestions and feedback are welcome!

### CODE REVIEW

**Comment by alexanderby** [comment]
Great work! Previously I was afraid to ask users location permission. But this solution with manual location is good.

Give me some time to take a look into it.

**Comment by khalilgharbaoui** [comment]
Exactly what i was looking for!

**Comment by alexanderby** [comment]
Sorry for the delay, currently I'm in a business trip, I will review it on Monday.

**Comment by alexanderby** [comment]
Thanks for the PR, really nice idea. Half-opaque dots near On/Off button are also great.

It is planned to clean-up the UI, because there are too many options.

**Comment by alexanderby** [comment]
You could add your name to GitHub account so that I could mention you in release notes.

**Comment by Kimbatt** [comment]
> 
> 
> Thanks for the PR, really nice idea. Half-opaque dots near On/Off button are also great.
> 
> It is planned to clean-up the UI, because there are too many options.

You're welcome; thanks for all the work!

**Comment by cbertoldi** [comment]
I've finally find these settings in Firefox on a desktop, but now I cannot find this in the Android version of the extension. Is this not supported for Android or am I just blind? @alexanderby

**Pull request merged**
