### PR TITLE
Update dark-sites.config to reflect domain name change (slither.io to slither.com)

### PR DESCRIPTION
**Pull request by Gitoffthelawn**

### CODE REVIEW

**Comment by Myshor** [comment]
maybe we will need to have them both... when I try to open .com it redirects me to .io

so I can not merge removing (changing from) .io to .com

**Comment by Myshor** [comment]
If it always ends with 

> > maybe we will need to have them both... when I try to open .com it redirects me to .io
> > so I can not merge removing (changing from) .io to .com
> 
> Are you sure you're seeing that right? When I go to the .io it redirects to http://slither.com/io and when I go to the .com it also goes to http://slither.com/io

Ok... When I open  the .com version it goes to http://slither.com/io but .io still goes to .io
obraz

For today I still recommend to have both entries.

**Comment by Gitoffthelawn** [comment]
Yes, if it's still going to .io for you, let's do that.  I wonder if it's browser-dependent or dependent on which server of theirs you connect to.  Either way, I agree, let's do both.

**Review by Gitoffthelawn — COMMENTED** [review]
Will add the original .io too

**Review by Gitoffthelawn — COMMENTED** [review]
Done!

**Pull request merged**
