### PR TITLE
Fix for t.bilibili.com

### LINKED ISSUE #7149: [Bug] t.bilibili.com white background
# Bug Report
 t.bilibili.com There will be a white background(background never changes dark),only in Microsoft Edge(ver.94.0.992.50)
## Bug Description

 t.bilibili.com There will be a white background(background never changes dark),only in Microsoft Edge(ver.94.0.992.50)
## Website Address

no
## Steps To Reproduce

- Go to t.bilibili.com.
- open the Dark Reader.
- Notice that when hovering over the t.bilibili.com,not the whole website turns dark. the blue backgorund does not change color.
## Expected Behavior

In the past it turns dark currently,whole dark including the background.
## Actual Behavior

3 days ago,the backgorund suddenly stayed light,never changed dark currently.
## Screenshots

${U{{C96I_E4}UV)@YI8RCO
## System Information

Microsoft Edge
ver.94.0.992.50 (64 位)
- OS: 
- Browser: 
- Dark Reader Version: 
windows10,Microsoft Edge ver.94.0.992.50 (64 位),dark reader ver.4.9.39

### PR DESCRIPTION
**Pull request by Gusted**
- Resolves #7149

### CODE REVIEW

**Comment by suixinex** [comment]
The latest version did not fix this bug

**Comment by Gusted** [comment]
I'm not able to reproduce this issue, make sure you got the latest fixes in dark reader.

**Comment by suixinex** [comment]
> I'm not able to reproduce this issue, make sure you got the latest fixes in dark reader.

Dark Reader is the latest version 4.9.43, The browser is the latest stable version of Edge

**Comment by Gusted** [comment]
Dev tools -> Reset.

**Comment by ShiratoriYuichi** [comment]
You need to log in to reproduce this problem. No problem occurred when I was not logged in.

**Comment by suixinex** [comment]
> Dev tools -> Reset.

Reset does not solve this problem

**Comment by Gusted** [comment]
> You need to log in to reproduce this problem. No problem occurred when I was not logged in.This problem has existed on my device for more than two months.

I cannot create a account, as it's seems like it's integrated with services(required to log in) that requires a lot more information that I'm willing to provide for a simple account.

If anyone can see where this background-image is coming from (from Dev-tools: ctrl + shift + i) a updated fix can be made.

**Comment by suixinex** [comment]
> > You need to log in to reproduce this problem. No problem occurred when I was not logged in.This problem has existed on my device for more than two months.
> 
> I cannot create a account, as it's seems like it's integrated with services(required to log in) that requires a lot more information that I'm willing to provide for a simple account.
> 
> If anyone can see where this background-image is coming from (from Dev-tools: ctrl + shift + i) a updated fix can be made.

Sorry, I have no relevant knowledge, I don't know if it is correct.
Web page source code: 
```
<!--
BUILT_AT: 2021年12月7日 07:42
-->
<!doctype html><html><head><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><meta charset="utf-8"><meta name="renderer" content="webkit"><meta name="description" content="bilibili是国内知名的视频弹幕网站，这里有最及时的动漫新番，最棒的ACG氛围，最有创意的Up主。大家可以在这里找到许多欢乐。"><meta name="keywords" content="B站,弹幕,字幕,AMV,MAD,MTV,ANIME,动漫,动漫音乐,游戏,游戏解说,ACG,galgame,动画,番组,新番,初音,洛天依,vocaloid"><meta name="application-name" content="哔哩哔哩"><meta name="format-detection" content="telephone=no"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black"><meta name="theme-color" content="#4393E2"><meta name="spm_prefix" content="444.41"><link rel="icon" href="//www.bilibili.com/favicon.ico"><link rel="apple-touch-icon" href="//www.bilibili.com/favicon.ico"><link rel="apple-touch-icon-precomposed" href="//static.hdslb.com/mobile/img/512.png"><title>动态首页-哔哩哔哩</title><script src="https://s1.hdslb.com/bfs/seed/jinkela/short/config/biliconfig.js"></script><script src="https://static.hdslb.com/js/jquery.min.js"></script><script src="https://s1.hdslb.com/bfs/cm/cm-sdk/static/js/bili-collect.js"></script><script src="//www.bilibili.com/gentleman/polyfill.js?features=Promise%2CObject.assign%2CString.prototype.includes%2CNumber.isNaN"></script><script src="//s1.hdslb.com/bfs/static/jinkela/long/js/sentry/sentry-5.2.1.min.js"></script><script src="//s1.hdslb.com/bfs/static/jinkela/long/js/sentry/sentry.vue.js"></script><link href="//s1.hdslb.com/bfs/static/blive/blfe-dynamic-web/static/css/vendors~517db8eb.0.28fed353.css" rel="stylesheet"><link href="//s1.hdslb.com/bfs/static/blive/blfe-dynamic-web/static/css/vendors~648587e9.1.28fed353.css" rel="stylesheet"><link href="//s1.hdslb.com/bfs/static/blive/blfe-dynamic-web/static/css/index.28fed353.css" rel="stylesheet"></head><body><div id="app" :style="{marginTop: appMarginTop}"><home></home></div><script src="//s1.hdslb.com/bfs/seed/jinkela/short/auto-append-spmid.js"></script><script src="//s1.hdslb.com/bfs/static/blive/blfe-dynamic-web/static/js/vendors~517db8eb.28fed353.js"></script><script src="//s1.hdslb.com/bfs/static/blive/blfe-dynamic-web/static/js/vendors~648587e9.28fed353.js"></script><script src="//s1.hdslb.com/bfs/static/blive/blfe-dynamic-web/static/js/index.28fed353.js"></script></body></html>
```
In the source code file t_bilibili_default.html -> [s1.hdslb.com/bfs/static/blive/blfe-dynamic-web/static/css/index.28fed353.css](https://s1.hdslb.com/bfs/static/blive/blfe-dynamic-web/static/css/index.28fed353.css) found background-image, the file name is background.bc725153.png
I hope these are useful for this
<https://s1.hdslb.com/bfs/static/blive/blfe-dynamic-web/static/img/background.bc725153.png>

**Comment by ShiratoriYuichi** [comment]
Thank you,I saw this picture, but I don’t know how to modify the css file and make it take effect.
谢谢，我看到这个图片了，但是不知道怎么对css文件修改，并让它生效。

**Comment by thouser8** [comment]
> Thank you,I saw this picture, but I don’t know how to modify the css file and make it take effect. 谢谢，我看到这个图片了，但是不知道怎么对css文件修改，并让它生效。

In fact,Dark Reader_4.9.4_can be useful......Like this:
image
So the question is,everytime I start the broswer(chrome and microsoft edge,the lateset version) it undates Dark Reader from chrome.google.com/webstore and,oh no......

**Pull request merged**
