### PR TITLE
Update dynamic-theme-fixes.config

### PR DESCRIPTION
**Pull request by derflasher**
I provide teltarif in darkmode for dynamic filtering.
Convince yourself:
https://www.teltarif.de/

### CODE REVIEW

**Review by Gusted — COMMENTED** [review]
I don't really like this fix nor how dark reader is handling this website. It seems to have some bugs which is preferred to be fix within the source code.

**Comment by derflasher** [comment]
Why don't you like the fix?

**Comment by Gusted** [comment]
> Why don't you like the fix?

Because the site is special. It also uses the light themed background-image. Which is common to have removed in the fix so the body will be once again dark. After that the fix is using `${}` whereby `var(--darkreader-neutral-background)` and `var(--darkreader-neutral-color)` is preferred.

**Comment by derflasher** [comment]
> Because the site is special.

That's why we need special handling.

**Review by Gusted — APPROVED** [review]
Good for now. Il be looking into this special site soon.

**Pull request merged**
