### PR TITLE
Updated drive.google.com/file

### PR DESCRIPTION
**Pull request by kohmy2036**
Updated origin URL of images of the toolbar buttons

### CODE REVIEW

**Review by Gusted — APPROVED** [review]
Thank you!

**Comment by kohmy2036** [comment]
You're welcome :)

**Comment by kohmy2036** [comment]
It looks like they went back to using `v-sprite33.svg`

**Comment by Gusted** [comment]
> It looks like they went back to using `v-sprite33.svg`

I noticed. Will open a PR to revert the changes.

**Pull request merged**
