### PR TITLE
Fixed Jira issue headers to show correct background color

### PR DESCRIPTION
**Pull request by sdo91**

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @sdo91 
Could you give an example link?

**Comment by Gusted** [comment]
@sdo91 ^

**Comment by sdo91** [comment]
Hmm, not sure about an example link. It would look something like this: https://mycompanyname.atlassian.net/browse/theissuenumber

**Comment by Gusted** [comment]
Could you give an screenshot Before and After, you can of course redact sential info I just need to see how it looks like after the fix.

**Pull request merged**
