### PR TITLE
Make Facebook icons more legible

### PR DESCRIPTION
**Pull request by prstorero**
Makes the Facebook icons in the top bar more legible for the dynamic theme engine.

Before: 
image

After: 
image

### CODE REVIEW

**Comment by alexanderby** [comment]
They become light, but when you click on them they become dark.

**Comment by prstorero** [comment]
I made changes with a new commit that correct the dark images for the clicked version as well.

**Comment by alexanderby** [comment]
There is a problem with earth icon, when you click it the content in popup becomes inverted and it seems like filters are applied to other popups twice.

Overall you should only apply CSS filters to void elements (icons, schemes, canvases, SVGs) and avoid applying filters to text blocks and photos. This way Filter and Filter+ work, but we are trying to avoid it in Dynamic mode.

If it's hard to do it for Facebook, leave it as is. Our image analysis will be improved to be able to handle sprite images like this https://www.facebook.com/rsrc.php/v3/y4/r/Sfw9IoCZwGA.png

**Comment by prstorero** [comment]
Strange, it worked for me when I opened it

image

But I understand you would rather approach this with the image analysis instead.

**Pull request closed without merging**
