### PR TITLE
Add manen.me to dark sites

### PR DESCRIPTION
**Pull request by manen**

### CODE REVIEW

**Comment by Gusted** [comment]
White to my eyes
image

**Comment by manen** [comment]
It uses media queries, if that's not enough I'll change it to dark-only

**Comment by Gusted** [comment]
> It uses media queries, if that's not enough I'll change it to dark-only

The list is exclusively for dark-only sites.

**Comment by manen** [comment]
Okay, it's dark now

**Review by Gusted — APPROVED** [review]

**Pull request merged**
