### PR TITLE
poeditor.com fix

### PR DESCRIPTION
**Pull request by maximmax42**

### CODE REVIEW

**Review by arche-dev — CHANGES_REQUESTED** [review]
```css
.chart img
```

Make it one selector per line, something like:

```css
.someselector
h1
```

**Comment by Gusted** [comment]
> ```css
> .chart img
> ```
> 
> Make it one selector per line, something like:
> 
> ```css
> .someselector
> h1
> ```

I'm not sure what we are talking about but `.chart img` looks good into me. As I don't assume you want to invert every `img` which I won't be merging.

**Comment by maximmax42** [comment]
Well, there's only one img inside chart class that needs to be inverted. I can change it to `.chart > img` but .chart only has one layer of child objects anyway, so `>` would be redundant.

**Comment by Gusted** [comment]
In that case I don't see @arche-dev relevance.

**Review by Gusted — APPROVED** [review]
Thank you for your contribution!

**Comment by arche-dev** [comment]
> I'm not sure what we are talking about but `.chart img` looks good into me. As I don't assume you want to invert every `img` which I won't be merging.

Ah, makes sense

**Pull request merged**
