### PR TITLE
Fix bugs.chromium.org (with a report of an issue)

### PR DESCRIPTION
**Pull request by NguyenASang**
### What I fixed
Actually the whole page, a lot of modifications so I can't remember all of it.

### What I can't fix

Weird background color:

image

Ultra shiny separators:
image

...

### Problem with "shadow-root"
To fix [this website](https://bugs.chromium.org) with bunch of "shadow-root", the most thing I can do is change the root color. Although Dark Reader supports modifying "shadow-root" child elements, it actually doesn't work in some cases. 

Proof:

https://user-images.githubusercontent.com/87893636/234637639-7b3e4592-0558-4478-a9e8-0b9aa1952238.mp4

But somehow, modifying attribute of "input#searchq" still works although it's under a "shadow-root".

I hope you @Gusted can take a look at this.

### CODE REVIEW

**Comment by NguyenASang** [comment]
@alexanderby Hello, what about the issue I mentioned ?

**Comment by bershanskiy** [comment]
> Hello, what about the issue I mentioned ?

This issue is caused by Dark Reader not handling deeply nested shadow DOM, I'll post an update once I find a good fix for this.

**Comment by NguyenASang** [comment]
Thank you very much.

**Comment by bershanskiy** [comment]
@NguyenASang I created a PR #11212 fixing this. I provided an explanation of the bug within it. Now I just need to add unit tests and test it for a bit more.

I expect the fix to be available in the next release, which we probably will make available this week.

**Pull request merged**
