### PR TITLE
Improve Image analyzing. 

### PR DESCRIPTION
**Pull request by Gusted**
- It's improved? It still works and I noticed using the options for specific coordinates is a lot slower than using the basic coordinates.
- This PR is mostly targetted for website e.g. Gmail which has a great impact because getImageData and drawImage is slow.

### CODE REVIEW

**Comment by alexanderby** [comment]
Strange PR. So, my solution was to set the canvas at maximum of 32x32 pixels for performance reasons. If image is smaller, it will be drawn without losses and native size pixels will be analyzed. If it is larger than 32x32, it will be downscaled to fit there. Natural size can be huge, so analyzing every pixel should be very slow.

**Comment by Gusted** [comment]
> Natural size can be huge, so analyzing every pixel should be very slow.

Downside of that somehow it's decreasing the performance of canvas functions.

**Comment by alexanderby** [comment]
Do you mean that downscaling an image is slow? If so, then the image could be painted in its real size, but some rows and columns can be skipped, e.g. `const xStep = Math.max(1, Math.floor(width / 32)); ... x += xStep`.

But a proper benchmark should be done to ensure this is a problem.

**Comment by Gusted** [comment]
> Do you mean that downscaling an image is slow? 

It seems to be. Or just the rapid repainting of different images. 

> But a proper benchmark should be done to ensure this is a problem.

Agreed.

**Comment by Gusted** [comment]
Will be succeeded by an better and more improved PR.

**Pull request closed without merging**
