### PR TITLE
Fix for *.webex.com

### PR DESCRIPTION
**Pull request by EnricoTirri**
add *.webex.com

### CODE REVIEW

**Comment by Myshor** [comment]
Can you share some screenshots what exactly you fixed here? I signed in went through all free webex things and all was already dark so I do not know what exactly you want to fix.

**Comment by EnricoTirri** [comment]
When I open a recording of my organization the body of the page is not inverting the color, the "body" CSS part is to ensure it to invert dark, the ".wxp-chapter-bar-item-progress" part is to set an accent color to the recording bar progress, that otherwise would be of a dark blue-ish color that is not so visible 
before
after

**Comment by EnricoTirri** [comment]
I think that this is the same for all organizations that use webex recording database, so I've set the CSS to use all sites that uses the ".webex.com" address

**Comment by EnricoTirri** [comment]
If you want to find out what is not working I think I can provide you a copy of HTML file of the page if it can be useful

**Comment by Myshor** [comment]
I was more aware of forcing background into body but I didn't find any issues for that.

Merging. 😉

**Comment by EnricoTirri** [comment]
Perfect thanks

**Pull request merged**
