### PR TITLE
Fix for accounts.hetzner.com

### PR DESCRIPTION
**Pull request by felixonmars**
- Invert dropdown menu icons

Before:
image
After:
image

### CODE REVIEW

**Review by Oreloth — CHANGES_REQUESTED** [review]
I suggest you to add following domains to cover entire Hetzner web network.

```
accounts.hetzner.com
dns.hetzner.com
konsoleh.hetzner.com
robot.hetzner.com

INVERT
.top-bar-link > img

================================

```

**Comment by felixonmars** [comment]
They are not all using the same CSS though. I have another entry for `robot.` for now.

**Comment by wan7teen-ping** [comment]
First step

Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g

Pada Jum, 7 Okt 2022, 7:51 PM Felix Yan ***@***.***> menulis:

**Comment by Oreloth** [comment]
[wan7teen-ping](https://github.com/wan7teen-ping) reported for abusive spam. Thanks to do it somewhere else.
===================================
About Hetzner's CSS, yeah I didn't know, well I'm gonna try to adapt code to fix entire Hetzner backsite.

**Review by Gusted — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
