### PR TITLE
Add linku.la to dark sites list

### PR DESCRIPTION
**Pull request by Drogobo**
nimi.li, linku.la, drogobo.com

### CODE REVIEW

**Comment by bershanskiy** [comment]
Hi, I see that one of these is your own site. If I understand correctly, you own the repository https://codeberg.org/Drogobo/pages

Could you please add the following to your page to tell Dark Reader to disable itself?
```html
<head>
    <meta name="darkreader-lock">
</head>
```

**Comment by bershanskiy** [comment]
Hi, I removed two sites because:
 - `drogobo.com` is better served by adding a `<meta>` tag to it
 - `nimi.li` is not dark be default

**Comment by bershanskiy** [comment]
@Drogobo I created a PR to your site'a repository here: https://codeberg.org/Drogobo/pages/pulls/1

**Comment by Drogobo** [comment]
Thank you very much!

**Pull request merged**
