### PR TITLE
Invert embedded gist on Medium.com

### PR DESCRIPTION
**Pull request by karvotch**

### CODE REVIEW

**Comment by Gusted** [comment]
Example Link?

**Comment by karvotch** [comment]
https://medium.com/hackernoon/learn-c-multi-threading-in-5-minutes-8b881c92941f

**Comment by Gusted** [comment]
> https://medium.com/hackernoon/learn-c-multi-threading-in-5-minutes-8b881c92941f

Don't see any CSS with .gist

**Comment by karvotch** [comment]
> > https://medium.com/hackernoon/learn-c-multi-threading-in-5-minutes-8b881c92941f
> 
> Don't see any CSS with .gist

Scroll down until you see a github frame embedded (they load in while scrolling through the page). I can't find the specified css file for these divs. Sorry, didn't know they load in while scrolling.

**Comment by Gusted** [comment]
And what is the logical sense to have the Gist white again? as It's just iritating my eyes...

**Comment by karvotch** [comment]
> And what is the logical sense to have the Gist white again? as It's just iritating my eyes...

That css made the gist invert when I turned on darkreader. The readme states to state the color before you invert.

**Comment by Gusted** [comment]
> > And what is the logical sense to have the Gist white again? as It's just iritating my eyes...
> 
> That css made the gist invert when I turned on darkreader. The readme states to state the color before you invert.

I can make out of this sentences 2 things

1.  You turned darkreader on while browsing the site? Aka After loading the site?
2. The README states that you fix the color of something that isn't dark or dark isn't right. Or just make a issue for it and let others deal with it.

**Comment by karvotch** [comment]
> > > And what is the logical sense to have the Gist white again? as It's just iritating my eyes...
> > 
> > 
> > That css made the gist invert when I turned on darkreader. The readme states to state the color before you invert.
> 
> I can make out of this sentences 2 things
> 
>     1. You turned darkreader on while browsing the site? Aka After loading the site?
> 
>     2. The README states that you fix the color of something that isn't dark or dark isn't right. Or just make a issue for it and let others deal with it.

Yes, seems to not work when turning darkreader on after loading the page.

**Comment by Gusted** [comment]
If not all but most darkreader users don't toggle it when mid-site so far I know. 

I just checked I toggled it mid-site and The gist just is being darken like normal..
I don't see any issue here that could been resolved with this patch..

**Comment by karvotch** [comment]
Yea, thanks for the clarification.

**Pull request closed without merging**
