### PR TITLE
Update dark-sites.config

### PR DESCRIPTION
**Pull request by sprinkledcheese**

### CODE REVIEW

**Comment by sprinkledcheese** [comment]
Earlier you removed some sites. Is there certain criteria that needs to be filled? @Gusted 
The following domains have dark/black theme by default except the specific pages I mentioned:
https://www.deviantart.com/users/login
https://www.epicgames.com/account

**Comment by Gusted** [comment]
Yes their are certain criteria some had a white cloudflare ddos protection page others had for my opinion not dark, before we gat users complains... And others hadn't dark theme by default.

**Comment by sprinkledcheese** [comment]
So isn't there any way to add the domain with those pages as exception?

**Comment by Gusted** [comment]
No, *Yet* I'm working a new URL matching so after that I can thoses pages with some exceptions.

**Comment by sprinkledcheese** [comment]
Also I can't find any issues with these sites: 
blackhatworld.com
coolguid.es
eleaks.to
imge.to
pahe.in
pahe.me
pahe.ph
reveddit.com
termbin.com
teamos-hkrg.com
snipboard.io

Am I missing something?

**Comment by Gusted** [comment]
They have or non-darkend colors or they have too much white elements.

**Comment by Gusted** [comment]
They have or non-darkend colors or they have too much white elements.

**Pull request merged**
