### PR TITLE
Add CSS for Medium

### PR DESCRIPTION
**Pull request by aguspdana**
Update background of highlighted text.
Previously light background with light text color.
Updated for domain medium.com and medium.economist.com.

### CODE REVIEW

**Comment by risualiser** [comment]
I think you can reduce it by 2 times:
```
medium.com
medium.economist.com
CSS
.markup--quote.is-targeted,
.markup--quote.is-other {
background-image: linear-gradient(to bottom, rgb(76, 76, 76), rgb(76, 76, 76));
}
```
But it doesn't cause any changes on my side, can you make a screenshot of it?

**Comment by risualiser** [comment]
This code is disappearing when I try to put in Dynamic Theme Editor (i don't think that CSS rules work in this theme engine).
For me, markup quotes look good now.

markup quotes

And bad after your changes (Filter mode).

filter changes

**Comment by alexanderby** [comment]
Dynamic mode doesn't support `CSS` yet, but I will add this option soon as far as some issues are hard to fix.

**Comment by alexanderby** [comment]
Custom CSS in Dynamic fixes was added, but a year passed. Please submit a new PR if needed.

**Pull request closed without merging**
