### PR TITLE
pornhub.com - A friend ask me to do

### PR DESCRIPTION
**Pull request by Gusted**
A friend of mine said it has dark theme by default and no white theme

### CODE REVIEW

**Comment by Kurtoid** [comment]
The project author doesn't seem to be accepting "adult" sites in this project. See https://github.com/darkreader/darkreader/pull/1981#issuecomment-598118499

**Comment by Gusted** [comment]
Hmm

**Comment by alexanderby** [comment]
My best wishes to your friend, but this is true. Policemen are happy to improve the stats by resolving such "crimes". I don't know if the domain name is enough to be considered as a link, but there are many absurd cases in Belarus, like arresting a man with muteness for swearing a policeman, or fining a woman for leaving a "disgusting" comment under an adult video. So I prefer to avoid such domain names just in case.

**Comment by Gusted** [comment]
> My best wishes to your friend, but this is true. Policemen are happy to improve the stats by resolving such "crimes". I don't know if the domain name is enough to be considered as a link, but there are many absurd cases in Belarus, like arresting a man with muteness for swearing a policeman, or fining a woman for leaving a "disgusting" comment under an adult video. So I prefer to avoid such domain names just in case.

Ah that kind of policemen don't worry get the feeling. Some local police here are just hunting for stuff they can do like a misplaced bike on a house property :eyes: Don't worry, I respect it. Just in case clear your history. for this issue if you see the title :/

**Comment by alexanderby** [comment]
@Gusted You wrote this title, now you'd better be afraid of Belarusian police :) Well, I see that many local news websites have a domain name on screenshots with PH users' stats, maybe I'm more paranoidal than they are.

**Comment by Gusted** [comment]
Another Country I can't go to smh. Local news website can use VPN or Tor or something like that. or It's just police covers the media that some shady :eyes:

**Pull request closed without merging**
