### PR TITLE
Proposal for Issue Templates Overhaul

### PR DESCRIPTION
**Pull request by DJ-Katalina**
I am proposing an overhaul of all 5 current issue templates. I have worked on consistency, clarity, general grammar / spelling / typo corrections, etc.

Thank you. 👍

### CODE REVIEW

**Comment by Gusted** [comment]
Could we have 1 PR for all this matter. I don't see the necessary of doing them individually, it's going to cost more time for the both of us.

**Comment by DJ-Katalina** [comment]
My apologies, I didn't know if there was a way to do multiple files in one.

**Comment by DJ-Katalina** [comment]
I can definitely try to resubmit all 5 files in one request. How do you want me to proceed in this matter?

**Comment by Gusted** [comment]
> My apologies, I didn't know if there was a way to do multiple files in one.

I suggest looking into using `git` and cloning this repo locally. That way you can submit "commits" with multiple files. It's could be too advanced for the average user. So for some workaround:

- Create a new branch from the master commit. In this case you could just use this one: https://github.com/DJ-Katalina/darkreader/tree/patch-2

And from their one you can edit the current files, so they would be in the same branch and show up in 1 PR, this one.

**Comment by DJ-Katalina** [comment]
Ok, I understand. Thank you so much for this help! I will resubmit 1 PR with all 5 files.

**Pull request closed without merging**
