### PR TITLE
Add  xeiaso.net to dark sites

### PR DESCRIPTION
**Pull request by BANOnotIT**

### CODE REVIEW

**Comment by bershanskiy** [comment]
Hi, this site does not appear to be using dark mode by default. Or am I missing something?

**Comment by BANOnotIT** [comment]
image
It is dark by default for me.

**Comment by Gusted** [comment]
Because it depends on the user's chosen color scheme:

image


Thank you for your PR, closing.

**Comment by KaKi87** [comment]
@BANOnotIT Added to my [Dark Reader dynamic blacklist](https://git.kaki87.net/KaKi87/userscripts/src/branch/master/darkReaderDynamicBlacklist/README.md) userscript in the *System* category.

**Pull request closed without merging**
