### PR TITLE
joemonster.org hard fixes

### PR DESCRIPTION
**Pull request by FadeMind**
Hard workaround messy CSS

https://joemonster.org

### CODE REVIEW

**Review by Gusted — COMMENTED** [review]
Seems more like this has to be fixed within dark reader

**Comment by Gusted** [comment]
As had some good amount of work onto the variables implementation code - I came across this PR again, but I don't remember what's broken as I currently don't see anything to be fixed. @FadeMind is the site good for you?

**Comment by FadeMind** [comment]
Default (without this PR fix) dark reader look:




It is not good. Some hard coded are ugly. Thats why I made hardcoded PR. 

CSS on this site is nightmare. 

This PR fix mostly all major issues visuals.

**Comment by Gusted** [comment]
This could be me but I don't see most of the issues that's are being shown, other than some of the more yellow elements not being read-able.

**Pull request closed without merging**
