### PR TITLE
Update dynamic-theme-fixes.config

### PR DESCRIPTION
**Pull request by ynakao**
Fixed inversion issue at https://prosody.im/.

### CODE REVIEW

**Comment by alexanderby** [comment]
This website looks well for me, maybe it was some temporary network error.

**Comment by ynakao** [comment]
Hmm... I tried again at fresh installed Chromium with Dark Reader add-on only, it worked fine. But at Dark Reader + Firefox, inversion behavior seems weird. Sometimes worked sometimes didn't work at all. 

More specific, I visited https://prosody.im/ at first time, Dark Reader inverted the background properly. However, clicked https://prosody.im/doc or something to look at other pages, then inversion didn't work anymore.

In addition, Alt+Shift+A toggling function sometimes didn't work at prosody.im pages.

Is this Firefox specific issue?

**Comment by alexanderby** [comment]
Looks like a bug.

**Comment by alexanderby** [comment]
Hi, a long time has passed but problem wit hFirefox is still there. Please use Filter mode for this website.

**Pull request closed without merging**
