### PR TITLE
Fix for blogs.windows.com

### PR DESCRIPTION
**Pull request by NguyenASang**

### CODE REVIEW

**Comment by Gusted** [comment]
Could you provide a small description of why this can be removed, without breaking anything?

**Comment by NguyenASang** [comment]
I removed the black background behind the Microsoft's logo and invert the color of the dot.

You can see the different in this [site](https://blogs.windows.com/windows-insider/2022/11/28/announcing-windows-11-insider-preview-build-22621-1020-and-22623-1020/)

**Comment by NguyenASang** [comment]
Before:

image

The color of the dots aren't suitable with the color of the text so I decreased the invert's value a bit 
And I also fixed the black color behind the background of the Microsoft's logo.

And the result:

image

**Comment by NguyenASang** [comment]
Before:

image

After:

image

**Review by Gusted — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
