### PR TITLE
reddit.com

### PR DESCRIPTION
**Pull request by sprinkledcheese**
- Removed wrong inversion.

### CODE REVIEW

**Comment by Gusted** [comment]
Why is it wrong?

**Comment by Gusted** [comment]
Btw side-note I will appreciate it if you name the PR's like `Fix for *site's url*`

**Comment by sprinkledcheese** [comment]
Ok, sure. I'll do that from next PRs.

**Comment by sprinkledcheese** [comment]
> Why is it wrong?
the logo is inverted.

**Comment by Gusted** [comment]
Which logo? I hadn't time to check yet

**Comment by sprinkledcheese** [comment]
the reddit logo in the header.

**Comment by Gusted** [comment]
Oh wow that's weird.

**Pull request merged**
