### PR TITLE
Adding automated extension submission via github action

### PR DESCRIPTION
**Pull request by louisgv**
Hi friends,

Love darkreader, I've been a user since forever. Was looking for some way to contribute, and thought that maybe an automated submission pipeline for the release archive could be helpful. 

I integrated 2 github actions that I created:
- [download-release-asset](https://github.com/plasmo-corp/download-release-asset): this action download release files 
- [bpp](https://github.com/marketplace/actions/browser-plugin-publisher) this action can submit the zip to the Chrome/Firefox (safari in the work) stores automatically 

The action in this PR is set to run manually from the github action tab, but we can tweak it to run as frequent as needed! The only thing you would need to create is a `SUBMIT_KEYS` github repository secret.

This secret is a json, with the schema defined [here](https://github.com/plasmo-corp/bpp/blob/main/keys.schema.json).

Here's a sample key for chrome and firefox:

```json
{
  "$schema": "https://raw.githubusercontent.com/plasmo-corp/bpp/main/keys.schema.json",
  "chrome": {
    "zip": "./darkreader-chrome-mv3.zip",
    "clientId": "123",
    "clientSecret": "456",
    "refreshToken": "789",
    "extId": "abcd"
  },
  "firefox": {
    "zip": "./darkreader-firefox.xpi",
    "extId": "123",
    "apiKey": "abcd",
    "apiSecret": "efgh"
  }
}

```

You can find instructions on how to get those keys in the schema, or if you use vscode, the schema should provide hint/intelisense when hovering over the json properties. If you need any help in setting up the keys, feel free to @ me! Otherwise if this doesn't seem necessary, feel free to close the PR :)

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @louisgv

What's the benefit of doing it automated then instead of doing it the manual way?

CC @alexanderby

**Comment by louisgv** [comment]
Hi @Gusted 

By `manually`, did you mean:
1. Download each zip file and open up the store submission page for each browser vendor, and drag and drop those zips to the input field and then hit submit for each store
2. Running a script internally from your local box to publish to each stores 

This action solves a pain point in each of the scenario above:
1. `bpp` automate the submission flow so you can just wait for review. This is esp useful for minor/patch update, when there's not a lot of change to the extension screenshot/description.
2. The publish secrets are not tied to your local box, allowing you or other approved contributor to trigger the run from the github action ci. This is useful in case where your box is nuked/compromised, or when you're away for vacation but a security patch need to be published for the extension

I'm working on Safari submission for it as well, hoping to land that soon!

**Comment by alexanderby** [comment]
Hi @louisgv! That's a very interesting PR. Unfortunately in our situation the review process is long and unpredictable. The Safari version is currently living separately from this repository too.

Also, in our situation with so many users, we are a target for hacker attacks. I don't fully understand how the plugin works, but it seems like I will not trust it doing such an important function.

**Comment by louisgv** [comment]
Hi @alexanderby - thanks for your respond!
> That's a very interesting PR. Unfortunately in our situation the review process is long and unpredictable. The Safari version is currently living separately from this repository too.

This action automate only the submission process, the review is still the same (on chrome/firefox/safari side). It can also be used to run in a private repo - the setup is as simple as adding a `.github` directory with the action workflow invoking this action

> Also, in our situation with so many users, we are a target for hacker attacks. I don't fully understand how the plugin works, but it seems like I will not trust it doing such an important function.

This is a valid concern! 

The action does the following work:
- Given a zip file
- Submit the zip to chrome store using the chrome's submission API: https://developer.chrome.com/docs/webstore/webstore_api/items/
- Sign and submit the zip to mozillla add-on using their sign api: https://github.com/mozilla/sign-addon/tree/master/src
- For Opera and Edge, it uses puppeteer to sim a headless chrome browser to send the zips to the extension page (following the approach in https://github.com/avi12/web-ext-deploy/

What I've done so far to mitigate security issue is to fork all the store submission code/module and improve/update their dependencies as well as improve them with typescript and official submission API where available. I'm working on the documentation for these module at the moment before making it public, but if you would like to audit the modules used in `bpp` yourself, I can make it public now :D 

Another way of ensuring integrity of your bundled extension is to have the build system produces a SHA256 hash of the files, add it into the latest release, then compare that hash to the store submitted archive. That way you can verify that this action did not tamper with the integrity of the extension (and neither did any actor within the CI pipeline). 

Thus, the only security issue would be supply chain attack to the `devDependencies`. It is possible that I can buy an expired domain to hack one of the npm module in the devDependencies to inject malicious code during the build - interesting to think about. Hopefully all the authors of the devDependencies are using 2FA for npm.

Let me know how else I can make the action more trust-worthy for use :)

**Comment by louisgv** [comment]
I have just finalized the documentation for all the modules behind `bpp` and open sourced them today:

- [Browser Market Submit](https://github.com/plasmo-corp/bms)
- [Mozilla Webstore Upload](https://www.npmjs.com/package/@plasmo-corp/mwu)
- [Chrome Webstore Upload](https://www.npmjs.com/package/@plasmo-corp/cwu)

**Comment by Gusted** [comment]
@alexanderby Do you have any interest in this (I don't have the secrets to set this up)? Otherwise I'm closing this...

**Comment by bershanskiy** [comment]
@louisgv Thanks for the PR, however we are not interested in delegating the actual publication process (and credentials) to GitHub Actions. The actual publication process is the only thing we do not plan to automate: it is the highest-privilege part of the whole development process and also comparatively speaking it does not take that much time (since publication process would still require manual testing and various QA stuff).

For reference, earlier this year [GitHub reported](https://github.blog/2023-01-30-action-needed-for-github-desktop-and-atom-users/) a breach of accounts responsible for signing releases of (their own) two major products, GitHub Desktop and Atom text editor. I personally do not consider usage of GitHub secrets service acceptable for storage of any significant data at all.

**Pull request closed without merging**
