### PR TITLE
Confirm before resetting changes

### LINKED ISSUE #2158: Confirmation before resetting custom css
For Static mode, you can specify your own css. So for websites that I go to frequently, I designed my own css. But one misclick and it resets to default, no way to get it back. So could anyone consider adding a confirmation box before reset? 

I could probably use some other custom css injecting addon for my use case, but I don't trust it with the permission to access all my data.

### LINKED ISSUE #4885: [Feature Request] Too Easy to Reset the Dynamic Theme Editor
# Feature Request

## Is your feature request related to a problem? Please describe
The `Reset` button in the Dynamic Theme Editor is too easy to click accidentally due to its placement next to `Apply`.  Doing so resets all changes ever made, and there appears to be no way to revert.

## Describe the solution you'd like
Some ideas:

- Make the Reset button harder to access (perhaps inside a menu)
- Add an "Are you sure?" dialog when resetting
- Add a way to view and revert to previous versions

### PR DESCRIPTION
**Pull request by Gusted**
- Ask for confirmation before resetting changes.
- Resolves #4885
- Resolves #2158

### CODE REVIEW

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/commit/cdd958787bd92ac771f3813a366ba234fe728284 [binaries.zip](https://github.com/darkreader/darkreader/files/5876674/binaries.zip)

**Comment by arche-dev** [comment]
Everything seems fine, to me atleast

**Comment by arche-dev** [comment]
I might found a bug, your edits before pressing apply are gone:

Removed a chunk of CSS fix, haven't pressed apply yet
image

I press reset changes, CSS fix comes back alive
image

I press `cancel`
image

---

Again, I'm removing a chunk, haven't pressed apply yet also

image

I press reset changes, the css I erased comes back alive
image

Now this time I press `ok` 
image

**Comment by arche-dev** [comment]
Now with pressing apply after removing a chunk:

I remove a chunk of fix
image

I press apply
image

Pressed reset, nothing happens
image

If I press ok, it resets and cancel its cancels
image
image

**Comment by Gusted** [comment]
That should be the behavior. As "Apply" is simply saving the text into the storage. However once we render the dialog it we re-render the text as well from storage.

**Comment by arche-dev** [comment]
> That should be the behavior. As "Apply" is simply saving the text into the storage. However once we render the dialog it we re-render the text as well from storage.

Oh, ok then

**Comment by Gusted** [comment]
It's a bit weird this whole behavior, but we don't want to "save" some changes if that person didn't save it.

**Pull request merged**
