### PR TITLE
DEL allegro.pl rules

### PR DESCRIPTION
**Pull request by FadeMind**
Allegro.pl using now native official dark mode IF dark theme is enabled in OS settings.

Your call.

### CODE REVIEW

**Comment by Myshor** [comment]
Maybe yes but not everyone would use Dark Mode with dark system settings. Deleting all entries for allegro will leave this people without fixes for light version.

I am not closing yet this issue because I need to check if the fixes is still needed for light version of allegro. As I checked now dark version the fixes don't mess that much and could be included in Dark Reader.

**Review by Myshor — CHANGES_REQUESTED** [review]
No changes needed but I change this because I don't want that accidently we just merge and remove all previous fixes.

**Review by Myshor — APPROVED** [review]
Seems to work fine with Dark Reader applied to light mode.

**Comment by FadeMind** [comment]
@Myshor Thanks

**Pull request merged**
