### PR TITLE
Fixes for blocket.se

### PR DESCRIPTION
**Pull request by rappos**
Blocket is Swedens biggest online second hand shop, with millions of visitors every week

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @rappos

Could you list a example URL where this fix is used?

**Comment by rappos** [comment]
> Hi @rappos
> 
> Could you list a example URL where this fix is used?

For example the drop-down on the main page has weird colorings without this fix. https://www.blocket.se/

Press the button that says "Hela Sverige", and you'll see hopefully

**Comment by Gusted** [comment]
> For example the drop-down on the main page has weird colorings without this fix. https://www.blocket.se/
> 
> Press the button that says "Hela Sverige", and you'll see hopefully

The dropdown is another issue, it's rendered by the OS and isn't local to just this site(e.g. see #8351)

**Comment by rappos** [comment]
OS problem, not darkreader problem

**Pull request closed without merging**
