### PR TITLE
Fix for baidu.com

### LINKED ISSUE #6480: [Bug] ditu.baidu.com's poi details pop have messed up styles after url rewrite
# Bug Report

## Bug Description

The poi details popup box (located on top-left part of the webpage, when you click on any poi on the map) have messed up styles, as long as there is a url rewrite (clicking on the map to show the box, or change to another poi, will trigger such rewrite), when darkreader is enabled.

## Steps To Reproduce

(In the screenshots below, I have removed all dynamic-theme-fixes for this site to make sure that they have no relationship with this bug. The bug is also present when the fixes are present, of course)
- Go to https://ditu.baidu.com/poi/%E4%B8%AD%E5%B1%B1%E5%85%AC%E5%9B%AD/@12725273.29,3558757.28,12z?uid=ecc3089e9e94bd7e28201a1e&info_merge=1&isBizPoi=false&ugc_type=3&ugc_ver=1&device_ratio=2&compat=1&querytype=detailConInfo&da_src=shareurl
- Note that the box is currently shown correctly like the following:
image
- Click on another park (green tree-like icon on the map, there are many)
- Note that the box is now messed up, like the following:
DeepinScreenshot_select-area_20210812145910
- Refresh the web page and see the correct info box of the new poi.

## Expected Behavior
The original functionality of the map should not be broken.

## Actual Behavior
One has to refresh the webpage to get the correct info box back.

## Screenshots
Already pasted in the steps above.

## System Information

- OS: Arch Linux x86_64 
- Browser: Firefox 91.0
- Dark Reader Version: 4.9.34

## Additional Context

n/a

### PR DESCRIPTION
**Pull request by Gusted**
- Resolves #6480

### CODE REVIEW

**Comment by Gusted** [comment]
@felixonmars Could you please test:
[firefox-binary-baidu-fix.tar.gz](https://github.com/darkreader/darkreader/files/6976534/firefox-binary-baidu-fix.tar.gz)

**Comment by felixonmars** [comment]
It seems all javascript functionality is broken with this change. The error in console is:

```
Uncaught TypeError: can't access property "getAttribute", o is undefined
    n https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    loadCss https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    <anonymous> https://webmap1.bdimg.com/wolfman/static/common/widget/ui/vcode/Vcode_d33db8a.js:1
    require https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    <anonymous> https://webmap0.bdimg.com/wolfman/static/common/pkg/init-pkg_9c79b65.js:18
    require https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    <anonymous> https://webmap0.bdimg.com/wolfman/static/common/pkg/init-pkg_9c79b65.js:5
    require https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    <anonymous> https://webmap0.bdimg.com/wolfman/static/common/pkg/init-pkg_9c79b65.js:15
    require https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    <anonymous> https://webmap0.bdimg.com/wolfman/static/common/pkg/libs_815de52.js:7
    require https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    o https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    define https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    <anonymous> https://webmap1.bdimg.com/wolfman/static/common/widget/ui/messageCenter/messageCenter_dae16c6.js:1
mod_5dbb339.js:1:18290
    n https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    loadCss https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    <anonymous> https://webmap1.bdimg.com/wolfman/static/common/widget/ui/vcode/Vcode_d33db8a.js:1
    require https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    <anonymous> https://webmap0.bdimg.com/wolfman/static/common/pkg/init-pkg_9c79b65.js:18
    require https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    <anonymous> https://webmap0.bdimg.com/wolfman/static/common/pkg/init-pkg_9c79b65.js:5
    require https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    <anonymous> https://webmap0.bdimg.com/wolfman/static/common/pkg/init-pkg_9c79b65.js:15
    require https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    <anonymous> https://webmap0.bdimg.com/wolfman/static/common/pkg/libs_815de52.js:7
    require https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    o https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    define https://webmap0.bdimg.com/wolfman/static/common/js/libs/mod_5dbb339.js:1
    <anonymous> https://webmap1.bdimg.com/wolfman/static/common/widget/ui/messageCenter/messageCenter_dae16c6.js:1```

**Comment by Gusted** [comment]
Thanks for noticing, it seems baidu takes advantage of the "live" behavior of the returned value which is something that vanilla javascript can't create/simulate(such that if a new element appears, that matches the tagName, it will be added onto that array/list).

I will need to give it another spin with some complicated Javascript's prototype behavior the correctly match this stupid behavior.

**Comment by Gusted** [comment]
This should hopefully fix the issue:
[firefox-binary-baidu-fix.tar.gz](https://github.com/darkreader/darkreader/files/6977085/firefox-binary-baidu-fix.tar.gz)

**Comment by Gusted** [comment]
> This fixes it!

*relieves*

Time to merge it, you can use the local copy for a while if you'd like until the next release(no ETA) is released.

Regards,
Gusted

**Comment by felixonmars** [comment]
It seems the local copy's dynamic theme editor doesn't save. Clicking "Apply" has no effect and after re-opening the changes are reverted.

I am not sure where this problem belong ._.

**Comment by Gusted** [comment]
> It seems the local copy's dynamic theme editor doesn't save. Clicking "Apply" has no effect and after re-opening the changes are reverted.
> 
> I am not sure where this problem belong ._.

You most likely hit the overwhelming storage issue(storage is saved but the browser kindly discards the saved data). You can give firefox a hard restart to solve the problem(or try to "reset" the devtools).

**Comment by felixonmars** [comment]
> > It seems the local copy's dynamic theme editor doesn't save. Clicking "Apply" has no effect and after re-opening the changes are reverted.
> > I am not sure where this problem belong ._.
> 
> You most likely hit the overwhelming storage issue(storage is saved but the browser kindly discards the saved data). You can give firefox a hard restart to solve the problem(or try to "reset" the devtools).

I have tried a lot of times (restarting, resetting, etc) but it's still 100% reproducible. Even editing anything, apply, and click "reset" will revert the change.

(The Mozilla addons version doesn't have this issue, but the unsigned local one always does.)

**Comment by Gusted** [comment]
Woops, misjudged the issue. Let's create a new issue for this(I can reproduce).

**Comment by Gusted** [comment]
#6494

**Pull request merged**
