### PR TITLE
Update the security policy for latest release

### PR DESCRIPTION
**Pull request by erkinalp**

### CODE REVIEW

**Comment by bershanskiy** [comment]
Frankly, I would rather replace this table with a simple link to https://github.com/darkreader/darkreader/releases and mention that some stores might have older versions published.

**Comment by bershanskiy** [comment]
I believe this was superseded by #10347, please comment if I'm wrong.

**Comment by erkinalp** [comment]
@bershanskiy Hmm, #10347 changes the policy slightly. More specifically, authorship info and call-to-PR is gone in it.

**Comment by bershanskiy** [comment]
@erkinalp I'm not sure what changes you are suggesting, if any. If you like, please open a new PR.

**Pull request closed without merging**
