### PR TITLE
Add darkreader-lock

### LINKED ISSUE #4325: [Feature Request] Provide opt-in HTML mechanism to indicate that my website is already dark
**Is your feature request related to a problem? Please describe.**
Normally the 'disable for site' functionality solves this problem, but I'm using the [Majestic](https://github.com/Raathigesh/majestic) local Jest GUI, and it opens on a random port every launch. So while Majestic is dark mode by default, this extension inverts it and causes it to become light mode very time I launch Majestic.

And I know I can do the workaround of forcing the port to a certain value with the Majestic CLI, but I think this problem has broader applicability. It would be nice for general website developers to be able to indicate to this extension that the site is already dark, so users don't have to fiddle this extension on/off quite so often while browsing the web.

**Describe the solution you'd like**
I would love to have some kind of HTML attribute I can put on the root, or meta tag I can add to the head, or something, that I can add to a page to tell this extension that the page is _already_ in dark mode, so the extension can automatically know not to run.

(Then, once that exists, I can submit a PR to Majestic to add that flag.)

**Additional context**

What Majestic normally looks like:
Screen Shot 2020-11-29 at 8 14 00 PM

What Majestic looks like while this extension is enabled:
Screen Shot 2020-11-29 at 8 14 14 PM

### LINKED ISSUE #4330: [Broken Website] alexn.org
I updated my website [alexn.org](https://alexn.org) to support a dark theme via a `@media (prefers-color-scheme: dark)` query.

Unfortunately Dark Reader messes with my design. And I tried adding these tags in `<head>`, for turning Dark Reader off, but it doesn't work (after reading #1114):

```html
<meta name="darkreader" content="41637b04c7ddb955e533a5c76d68a2c8">
<meta name="color-scheme" content="light dark">
```

Looking at this repository, I see there's a [dark-sites.config](https://github.com/darkreader/darkreader/blob/master/src/config/dark-sites.config) file, but it doesn't apply, since these websites seem to have a dark theme by default.

So how can I prevent Dark Reader from messing with my own dark theme?

PS: [twitter.com](https://twitter.com/) is another example with a theme that's changed by Dark Reader, even if they support a proper dark theme, and on Android the menu icons are gone.

PPS: thank you for all your hard work ❤️

---

**UPDATE** 

Tested with:

- Firefox 83.0 + 84.0b6 (Developer Edition)
- Chrome 87.0.4280.67

Screenshot of what I'm seeing in Firefox, on the desktop:

<https://user-images.githubusercontent.com/11753/100605126-21883500-3310-11eb-93f2-1f680ddd1aa6.png>

Screenshot of Firefox for Android:

<https://user-images.githubusercontent.com/11753/100605448-9c515000-3310-11eb-8deb-21ae9722b8af.jpg>

Here's the current design with Dark Reader off, which is what I expect to see, notice the colors:

<https://user-images.githubusercontent.com/11753/100605561-c571e080-3310-11eb-8c7d-3a24aa0c8f01.png>

### PR DESCRIPTION
**Pull request by Gusted**
- Add `<meta name="darkreader-lock">` to look for and if available remove Dark Reader.
- Resolves #4325
- Resolves #4330

### CODE REVIEW

**Comment by Yash-Singh1** [comment]
@Gusted Should the API add this tag in when it is enabled? I was having a problem of my site being double darkened, breaking some things inside it.

**Comment by Gusted** [comment]
> @Gusted Should the API add this tag in when it is enabled? 

No, because the API will detect the meta as well and the removes itself.

> I was having a problem of my site being double darkened, breaking some things inside it.

The normal `meta` of dark reader should handle that problem

**Comment by Yash-Singh1** [comment]
> The normal `meta` of dark reader should handle that problem

Do you mean?:
```html
<meta name="darkreader">
```

**Comment by Gusted** [comment]
No I mean
```html
<meta name="darkreader" content="Here some Psuudo random number">
```

**Comment by Apostolique** [comment]
Was there anything missing for this one to be merged?

**Comment by Gusted** [comment]
> Was there anything missing for this one to be merged?

Other than conflicting file that is pretty simple to solve. It's just waiting to get it reviewed by @alexanderby. Which due reasons, will take a while. Nor it's an really important feature as some others PR's.

**Review by hadialqattan — APPROVED** [review]

**Comment by voruti** [comment]
How is this different from `<meta name="darkreader" content="Here some Psuudo random number">`?

**Comment by Gusted** [comment]
> How is this different from `<meta name="darkreader" content="Here some Psuudo random number">`?

We will be looking for the darkreader-lock pro-actively whereby this meta is only checked at the startup to check we don't conflict with other instance of darkreader.

**Comment by Gusted** [comment]
Superseeded by: #9181

**Pull request closed without merging**
