### PR TITLE
Change approvement to approval

### PR DESCRIPTION
**Pull request by arielallon**
"Approvement" is an archaic version of the word.

### CODE REVIEW

**Comment by alexanderby** [comment]
Thanks. Did you see the Help page, what do you think about it?
https://github.com/darkreader/darkreader.org/blob/master/src/help/topics/en.md

**Comment by arielallon** [comment]
I hadn't seen it. It looks helpful (though at the moment it looks like the images are 404'ing?).

**Comment by alexanderby** [comment]
It is a Markdown file which is later transformed into HTML. Here you can see, how it looks, maybe there are some mistakes too https://darkreader.org/help/en/

**Comment by arielallon** [comment]
@alexanderby finally got around to taking a look at that page and fixing up some stuff: https://github.com/darkreader/darkreader.org/pull/27

**Pull request merged**
