### PR TITLE
Fix dark text on LinkedIn.com

### PR DESCRIPTION
**Pull request by sd2048**

### CODE REVIEW

**Comment by Gusted** [comment]
@Myshor Linkedin fixes are mostly your artwork 😛

**Review by Myshor — CHANGES_REQUESTED** [review]
.global-nav__primary-link-text
First: I did not touch it because it must be different when selected, hovered and in other status. With your proposal you always set one color to all states. I must reject.

The big ammount of buttons/links/etc.
I could think about accept but... It will break averything in light mode. So using light color should be:
color: $(rgba(246, 244, 241, 0.8));

Make the changes and I will approve.

**Review by Myshor — COMMENTED** [review]
Checked what you want to fix with that big ammount of classes... It's already fixed with my variable ingerention

:root {
    --color-text-low-emphasis: ${rgba(0,0,0,0.6)};
}

And will be included in new release.

**Comment by sd2048** [comment]
Okay, does that make this PR unnecessary?

**Comment by Myshor** [comment]
It seems... I just can't select something like "Not needed" 😉
BTW thanks for approach for the fix. 👍

**Comment by sd2048** [comment]
Got it, thanks.

**Pull request closed without merging**
