### PR TITLE
Update dynamic-theme-fixes.config for elearning.budiluhur.ac.id

### PR DESCRIPTION
**Pull request by neonr4in**
Apologise for wrong commit before, here is the correct one for elearning.budiluhur.ac.id.

CSS body color.

`color: ${black} !important;`

### CODE REVIEW

**Comment by Gusted** [comment]
I don't see any visible changes.

**Comment by Gusted** [comment]
@neonr4in Can you point out what you have changed?

**Comment by neonr4in** [comment]
Hello, it looks like that the inversion of body text working properly now without tweak. I can close this commit.

Sorry for wasting your time.

**Comment by Gusted** [comment]
It's never a waste of time!

**Pull request closed without merging**
