### PR TITLE
[NSFW] daftsex.com: don't touch logo

### PR DESCRIPTION
**Pull request by FadeMind**
Without fix:

After applying fix:

Please consider merging. Regards.

### CODE REVIEW

**Comment by Gusted** [comment]
NSFW site.

**Comment by FadeMind** [comment]
@Gusted `NSFW` yes.
For full white you need set gray 💯  otherwise will be:
Default:

With `INVERT .logo`:

With `INVERT .logo` and gray 💯 :

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/1981#issuecomment-598118499
https://github.com/darkreader/darkreader/pull/2255#issuecomment-613913514

**Comment by FadeMind** [comment]
@Gusted understood. Closing.

**Pull request closed without merging**
