### PR TITLE
Fix for youtube.com

### PR DESCRIPTION
**Pull request by Gusted**
So Darkreader Changes the variable of the Banner for no *logical* reason.

Related Issue: #2219 and #1530 (Aug 27, 2019)

# Before
As you can see It's changes the variable

# After

### CODE REVIEW

**Comment by KimiNoNaWaGithub** [comment]
Thanks for your fix but how can I apply that to Dark Reader?

**Comment by Gusted** [comment]
> Thanks for your fix but how can I apply that to Dark Reader?

Wait until 4.9.5 or open devtools and manually paste the fix

**Comment by KimiNoNaWaGithub** [comment]
> > Thanks for your fix but how can I apply that to Dark Reader?
> 
> Wait until 4.9.5 or open devtools and manually paste the fix

image

Ok, so this issue is back in 2021
System:
- Chrome 88.0.4324.182 64bit
- Windows 10 Pro 20H2 64bit
- Dark Reader 4.9.27

**Comment by Gusted** [comment]
HI @KimiNoNaWaGithub!

Thanks for letting me know #5101

Regards,
Gusted

**Pull request merged**
