### PR TITLE
Add keyframe support

### PR DESCRIPTION
**Pull request by Gusted**
1. It's being more used in the wild.

Would solve #2101 But was manual with `@keyframes` they are now also dropped.
Resolve #2590

https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes < Documentation I followed to get everything worked of how the CSS should look like.

The example will show it will infinty fade in the `block`.
It works with Dakreader Off and with this Patch. Without it, it will just fade out as we don't target the colors.

Example I used
[n.zip](https://github.com/darkreader/darkreader/files/4671882/n.zip)

### CODE REVIEW

**Comment by Gusted** [comment]
Possible bug with ModifyColorWithCachr they the second color e.g. White or black so fat I know would return the same color but just in hex format...

**Comment by ruffsl** [comment]
Could this be rebased with the merge conflicts resolved?

**Comment by Gusted** [comment]
Rebasing is harder than just rewriting this PR from scratch with the new logic.

**Comment by Gusted** [comment]
#3819 Done

**Pull request closed without merging**
