### PR TITLE
Update dynamic-theme-fixes.config

### PR DESCRIPTION
**Pull request by foul-fortune-feline**
Fixes transparent images on wikipedia (and presumably wikiless) by drawing a white background behind them

### CODE REVIEW

**Comment by thiemowmde** [comment]
This might work for some transparent images, e.g. SVGs that are nothing but some black lines on a transparent background. It's true that these don't look good on an inverted background. But this is not the only reason to make images transparent. The vast majority of transparent images on Wikipedia doesn't have such a problem but will look [significantly worse](https://lists.wikimedia.org/hyperkitty/list/wikitech-l@lists.wikimedia.org/message/2ORRNKDAU3YJ7EUCBRFXWV3CX6Y6E54Z/) with a white rectangle behind them. Please revert this and look into the problem in more detail.

The MultimediaViewer extension had the same problem, as well as the MinervaNeue skin. See e.g. [T59620](https://phabricator.wikimedia.org/T59620) and [T77201](https://phabricator.wikimedia.org/T77201).

One idea is to use a checkerboard instead, make it a hover effect (i.e. not permanently visible but only when hovering with the mouse), and apply it [only to certain image types](https://phabricator.wikimedia.org/diffusion/EMMV/browse/master/resources/mmv/ui/mmv.ui.canvas.less$63) that are known to have such problems.

**Comment by DocTaxon** [comment]
@foul-fortune-feline , @alexanderby Hi, there's no need for this change on Wikipedia pages. Please undo it. The behavior, to read dark SVGs on a DarkReader screen is very normal. The Wikipedia community doesn't want an important white background color. Transparency is important for anyone who works with SVG graphics. So please undo this change. We will appreciate it. Thank you!

**Comment by DocTaxon** [comment]
@alexanderby @kizule Thank you for the revert, but how can I see success? I updated the wikipage, reloaded it, switched DarkReader off and on and purged. But I have no success, the white background is still there (Chrome)

**Comment by DocTaxon** [comment]
> > @alexanderby @kizule Thank you for the revert, but how can I see success? I updated the wikipage, reloaded it, switched DarkReader off and on and purged. But I have no success, the white background is still there (Chrome)
> 
> Open DarkReader -> Settings -> Manage settings -> check "Synchronize sites fixes"

I don't find "Settings", sorry  :(

**Comment by kizule** [comment]
> > > @alexanderby @kizule Thank you for the revert, but how can I see success? I updated the wikipage, reloaded it, switched DarkReader off and on and purged. But I have no success, the white background is still there (Chrome)
> > 
> > 
> > Open DarkReader -> Settings -> Manage settings -> check "Synchronize sites fixes"
> 
> I don't find "Settings", sorry :(

Try to follow this: https://github.com/darkreader/darkreader?tab=readme-ov-file#site-fixes

**Comment by DocTaxon** [comment]
> check "Synchronize sites fixes"

I checked "Synchronize sites fixes" without any change, there's still the white background

**Comment by kizule** [comment]
Have you forced cache memory by refreshing the page with CTRL + Shift + F5?

**Comment by DocTaxon** [comment]
> Have you forced cache memory by refreshing the page with CTRL + Shift + F5?

It works!!! Okay, fine. Thanks a lot for any help

**Comment by alexanderby** [comment]
Please wait for an update to be reviewed (it can take 1-3 days).

**Pull request merged**
