### PR TITLE
omnivox.ca stuff

### PR DESCRIPTION
**Pull request by austinhuang0131**
#2673 3

### CODE REVIEW

**Comment by Gusted** [comment]
That's a quite a bit Changes. Can you link some URL's where I can see what it does?

**Comment by austinhuang0131** [comment]
No, because it's intranet, and also everything is _images_ (aka. pre-2010 internet) so the edit is very patchy. Screenshot (no personal detail):



* This only affects old design "Léa" pages. Dark Reader does the new-style pages fairly well.
* The left sidebar exists on every page, while the right sidebar doesn't (homepage only).
* Yes, there's a white box on the right, but you see, the website employs css `background-image` and img tag inconsistently, so can't fix that easily.

**Comment by austinhuang0131** [comment]
Comparison:

screencapture-www-mpo-ovx-omnivox-ca-cvir-doce-Default-aspx-2020-06-02-15_33_12

**Comment by Gusted** [comment]
Make sure if you go to light scheme on darkreader it's still looks good than I'm good to merge it.

**Comment by austinhuang0131** [comment]
screencapture-www-mpo-ovx-omnivox-ca-cvir-doce-Default-aspx-2020-06-02-15_38_44

**Comment by austinhuang0131** [comment]
screencapture-www-mpo-ovx-omnivox-ca-cvir-doce-Default-aspx-2020-06-02-15_38_44

**Comment by austinhuang0131** [comment]
note: have to redact all screenshots due to privacy

**Pull request merged**
