### PR TITLE
Fix for google.*/chrome

### PR DESCRIPTION
**Pull request by AndrewDaGuy**
Site: https://www.google.com/chrome/

Changes:
- Inverted everything that's retina-burning-white except the dark mode section

The amount of times I pressed reset accidentally and threw my desk out of the window: `1`

### CODE REVIEW

**Review by Gusted — COMMENTED** [review]
Not sure about this one to invert all those images.

**Comment by AndrewDaGuy** [comment]
Fixes in b25385427c2680dcc4a27893cb63bfe7da1c10f9 

---

https://www.google.com/chrome/
```CSS
[src^="/chrome/static/images/download-browser/pixel"]             /* Phones at the end of the page */
[src="/chrome/static/images/homepage/homepage_tools.png"] 
[src="/chrome/static/images/homepage/homepage_privacy.png"]
[src="/chrome/static/images/download-browser/big_pixel_phone.png"] /* Phone at the end of the page */
```

---

https://www.google.com/chrome/browser-tools/

```CSS
[src="/chrome/static/images/browser-by-google/pixel_slate_port_desktop.png"] /* Tablet at the start of the page */
[src^="/chrome/static/images/productivity/"]              /* Gmail and Doc Screens*/
[src="/chrome/static/images/gpay/slate.png"]              /* Google Pay image */
[src^="/chrome/static/images/google-translate/screen-"]   /* Google Trans Image for English and Greek */

```

---

https://www.google.com/chrome/browser-features/#

```CSS
[src="/chrome/static/images/features/big_phone_desktop.png"]    /* BIG Phone at the start of page */
[src="/chrome/static/images/features/phone_desktop.png"]        /* Phone at the start of page */
[src="/chrome/static/images/search-bar/chrome-ui_desktop.png"]  /* Search thingy */
[src="/chrome/static/images/reversible/password-check.png"]     /* Password check */
[src="/chrome/static/images/sync-incognito/chrome-ui-sync.png"] /* Sync image */
[src^="/chrome/static/images/be-more-productive/"]              /* Everything in the Be more productive section */
[src="/chrome/static/images/reversible/articles.png"]           /* The phone in articles */
```

**Review by Gusted — COMMENTED** [review]
Hopefully you know by now how to short some of the selectors.

**Comment by AndrewDaGuy** [comment]
> Hopefully you know by now how to short some of the selectors.

Ah, give me a sec

**Pull request merged**
