### PR TITLE
badboybill.com is dark

### PR DESCRIPTION
**Pull request by DJ-Katalina**

### CODE REVIEW

**Review by arche-dev — APPROVED** [review]
Dark Site Certified :+1:

**Comment by DJ-Katalina** [comment]
> 
> 
> Dark Site Certified 👍

Haha!

**Comment by DJ-Katalina** [comment]
I didn't mean to close and reopen this issue. Please process it as normal.

I can barely see straight. I need to go to bed. 🤣

**Comment by Gusted** [comment]
Don't stay up late! Anything can always be done the following/next day.

**Review by Gusted — APPROVED** [review]

**Pull request merged**
