### PR TITLE
Updated dynamic-theme-fixes.config YouTube's Copyright page

### PR DESCRIPTION
**Pull request by TheAlienDrew**
Fixed the background SVG (changed color to black and converted it to URI to use)
Fixed the logo that would appear above this svg by inverting it.

### CODE REVIEW

**Comment by alexanderby** [comment]
Is it possible to add this fix to `youtube.com` and replace base64 image with `INVERT` rule?

**Comment by TheAlienDrew** [comment]
Try the invert yourself... It inverts the entire element, which means
everything in the body. That's why I did it the base64 way.

**Comment by alexanderby** [comment]
Then let's use `background-image: none !important;`.

**Comment by TheAlienDrew** [comment]
Going to close this and do another pull request in the right area

**Pull request closed without merging**
