### PR TITLE
Fix for pipewire.com

### LINKED ISSUE #7599: [Broken Website] https://pipewire.org/
# Broken Website Report

## Website Address
https://pipewire.org/

## Steps To Reproduce

- Go to https://pipewire.org/
- Notice differences when using and not using Dark Reader with and without OS Dark / Light Modes and with and without Firefox System Theme Auto / Firefox Dark Theme.

## Expected Behavior
To be able to use Dark Reader on this website while using OS Dark Mode and Firefox Dark Theme without being blinded by the issue causing this. (Refer to Screenshots and Additional Context for more information)

## Actual Behavior
Being blinded by the issue causing this while trying to use Dark Reader on this website with OS set to Dark Mode and Firefox using Dark Theme. (Refer to Screenshots and Additional Context for more information)

## Screenshots
Windows Light Mode - Firefox System Theme Auto - No Dark Reader:
pipewire-windows-light-theme-firefox-system auto-theme-no-dr

Windows Light Mode - Firefox System Theme Auto - With Dark Reader:
pipewire-windows-light-theme-firefox-system auto-theme-with-dr

Windows Light Mode - Firefox Dark Theme - No Dark Reader:
pipewire-windows-light-theme-firefox-dark-theme-no-dr

Windows Light Mode - Firefox Dark Theme - With Dark Reader:
pipewire-windows-light-theme-firefox-dark-theme-with-dr

Windows Dark Mode - Firefox System Theme Auto - No Dark Reader:
pipewire-windows-dark-theme-firefox-system auto-theme-no-dr

Windows Dark Mode - Firefox System Theme Auto - With Dark Reader:
pipewire-windows-dark-theme-firefox-system auto-theme-with-dr

Windows Dark Mode - Firefox Dark Theme - No Dark Reader:
pipewire-windows-dark-theme-firefox-dark-theme-no-dr

Windows Dark Mode - Firefox Dark Theme - With Dark Reader:
pipewire-windows-dark-theme-firefox-dark-theme-with-dr

## System Information

- OS: Windows 10 21H2 (19044.1387)
- Browser: Firefox 95.0
- Dark Reader Version: 4.9.43

## Additional Context
I am uncertain whether this is a Dark Reader bug or a Firefox bug or a website bug. My guess is that this website has very unusual code when it comes to detecting OS Mode or Firefox Theme. (I really have no clue, TBH). Please help me understand this, as I have been going insane trying to troubleshoot this issue for quite a while. This issue has to do with Dark Reader on this website and different combinations of Windows Modes (Dark / Light) and different Firefox Themes (Dark Theme vs. System Theme Auto). I have included several screenshots with detailed titles to help understand this issue. If this is a Dark Reader bug, is this something that can be corrected in the code, dynamic theme fixes or some other method? Thank you!

### PR DESCRIPTION
**Pull request by Gusted**
- Resolves #7599

### CODE REVIEW

**Comment by q1800** [comment]
@Gusted Hi! Thank you for the fix. One small problem tho, the fix is needed for pipewire.**org**, not pipewire.**com** 😄

**Comment by Gusted** [comment]
Woops, use of habbit 😄

**Comment by Gusted** [comment]
#7614

**Comment by q1800** [comment]
Hahaha, no problem. The fix is working as intended now. Thank you very kindly! 😄

**Pull request merged**
