### PR TITLE
Add invert to Facebook logo in Instagram settings

### PR DESCRIPTION
**Pull request by busybox11**

### CODE REVIEW

**Comment by Gusted** [comment]
@Myshor could you test out this kne

**Comment by Myshor** [comment]
I don't use Instagram.

Even if I login with facebook to test It would be nice to have some example URL to check which facebook logo should be inverted or not.
I don't want to go through whole instagram to search it as I don't even use it.

So @busybox11 can you share some example URL that will help with checks?

**Comment by busybox11** [comment]
Yeah, I can do that. I left my house like 2 minutes ago, so I'll do it when I'll come back (if I remember to do it lol).

**Comment by busybox11** [comment]
Hey, I'm back.
See the facebook logo on the bottom left of the card.
image
This is the fix

image
This is without the fix

**Review by Myshor — COMMENTED** [review]
Ok... It works but as I know a little bit facebook family apps it's better to not use classes for selector as they can change very often. ;) I recommend using svg[aria-label*="Facebook"] instead. ;)

**Comment by Myshor** [comment]
Just check if it will work for you 'cause my aria-label was in Polish but I think all languages will include that "Facebook" pattern.

**Comment by busybox11** [comment]
Ookay.

**Comment by busybox11** [comment]
Yup, it works!

**Pull request merged**
