### PR TITLE
Made some CSS changes in order to smooth transition on the website

### PR DESCRIPTION
**Pull request by Kwispy222**
I was able to fix a large amount of what was mentioned in this issue (https://github.com/darkreader/darkreader/issues/12762).
Specifically, I was able to eliminate the lag time of swtitching on and off for the top bar and option sections of a new spreadsheet as described in the issue.

### CODE REVIEW

**Comment by Myshor** [comment]
Tested in on Firefox and I do not see any differences with flashing when this fix is applied in sitefixes or is not appled.

Still I see white flash before everything is set to dark.

As I do not see any changes after fix I leave it not merged.

**Comment by Kwispy222** [comment]
Interesting. @Myshor thanks for taking a look at this PR! Are you seeing any difference between current main branch and this branch? I installed my build from scratch on a fresh firefox install and I see that there is still white flash with the "t-formula-bar-input" but the rest of the top section (i.e. spreadsheet title, share button, bold/itallic/underline buttons, etc) switch immediately which is not the case when I was testing on the current main branch.

Thanks for any input you can give!

**Comment by Myshor** [comment]
As you mentioned the top section now I see this part is not flashing that much. OK. Starting unit tests if they pass I will merge. 😉

**Comment by Obsidianninja11** [comment]
This messes up the look of the header, and doesn't even help with flashing very much, since the main flash of the waffle grid can still happen.
Before: 
After:

**Comment by Myshor** [comment]
ok... I'm reverting as it won't help that much and causes problems.

**Pull request merged**
