### PR TITLE
Add GuruShots.com custom CSS

### PR DESCRIPTION
**Pull request by Karmalakas**

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @Karmalakas!

Can you link an URL where the CSS is made for?

Regards,
Gusted

**Comment by Karmalakas** [comment]
> Can you link an URL where the CSS is made for?

Hi :)

Not sure what link exactly you want :) When you log in to gurushots.com, your main page becomes [this one](https://gurushots.com/challenges/my-challenges/current) and there are challenges listed. So transparent background fixes grey background behind timers and neutral text color fixes the exposure meter arrow color on challenge voting popup.

It's a bit difficult to add a screenshot, because challenges vary and expire and I don't have any now, but I can make a screenshot of that arrow later.

I've had these style fixes for months now on my main PC :)

**Comment by Karmalakas** [comment]
Here's the Arrow without a fix
image

Here's with a fix
image

Sadly don't have now any running challenges with the specific timer that needs a fix to make a screenshot

**Review by Gusted — APPROVED** [review]
The CSS LGTM.

**Comment by Gusted** [comment]
Thanks!

**Pull request merged**
