### PR TITLE
Tom's hardware white-on-white fix

### PR DESCRIPTION
**Pull request by erkinalp**

### CODE REVIEW

**Comment by alexanderby** [comment]
Let's put it on hold, the JS fix is on it's way. Could you please share a link to double check if the problem you encountered is already fixed?

**Comment by erkinalp** [comment]
> Let's put it on hold, the JS fix is on it's way. 

This workaround also applies to older versions, though.

**Comment by alexanderby** [comment]
@Gitoffthelawn I've checked and everything seems fine on the latest build version.

**Comment by alexanderby** [comment]
Works well in v4.9.81.

**Pull request closed without merging**
