### PR TITLE
Create language he.config

### PR DESCRIPTION
**Pull request by refael722**
Retrying (time 2), after it fails.
Update: done.

### CODE REVIEW

**Comment by Gusted** [comment]
For which language is this?

**Comment by refael722** [comment]
For "Hebrew"
It is briefly written in the name of the file

**Comment by refael722** [comment]
@Gusted 
For "Hebrew"
It is briefly written in the name of the file

**Comment by refael722** [comment]
@Gusted
Thank you!

**Comment by Gusted** [comment]
@refael722 
Thank you for contributing 🗡️

**Pull request merged**
