### PR TITLE
Add pre-defined color-schemes

### PR DESCRIPTION
**Pull request by Gusted**
- Add a _first iteration_ contributing guide.
- Add a human readable config syntax and a parser with a lot of guards. Performance is around (150K Op/sec).
- Add _popular_ pre-defined color schemes to Dark Reader and be able to select them. If any of the colors are changed by the user the color-scheme option is reset as we _currently_ do not have this ability and should be done for a futher PR.
- Resolves

### CODE REVIEW

**Comment by Gusted** [comment]
> The syntax here looks a lot like YAML, so perhaps instead of re-implementing a special parser we could re-use a YAML library?

That would be possible - even though that will make it more out-of-sync with our current syntax-like configs.

Another thing is that we will have to "loop" twice trough it - once to parse the YAML and then to check for specifications errors within the defined YAML object, I'm not sure if that's able to be done within < 250 LOC as this parser without it's comments is already large in my opinion.

**Comment by bershanskiy** [comment]
Yes, this looks ready to merge (aside from a minor nit). Good job!

**Comment by metafates** [comment]
sorry if it's a silly question, but how can I use theses themes? I couldn't find an option to do, I'm really confused...

**Comment by Gusted** [comment]
Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.
    under Theme click See all options, Colors.

**Pull request merged**
