### PR TITLE
Add mobile01.com to dark sites

### PR DESCRIPTION
**Pull request by wzxu**

### CODE REVIEW

**Comment by Gusted** [comment]
Thank you for your contribution, unfortunately this site doesn't appear to be dark by default. Therefor it cannot be included into this list. Closing.

**Comment by wzxu** [comment]
> Thank you for your contribution, unfortunately this site doesn't appear to be dark by default. Therefor it cannot be included into this list. Closing.

Huh. It surely is for me… Weird. Tried it out on a few different browsers. I'm on macOS Monterey.

**Comment by wzxu** [comment]
It clearly has a default dark theme, as pictured. I wonder what's the cause it's not appearing on your side?
Screen Shot 2022-05-02 at 12 12 42 AM

**Comment by wzxu** [comment]
@Gusted Ah sh*t. Went back and re-read it again. Sorry, my bad. 😅

> All pages are dark by default regardless of the system's preferred color-scheme.

**Pull request closed without merging**
