### PR TITLE
Update dynamic-theme-fixes.config to fix logo on *.abc.net.au

### PR DESCRIPTION
**Pull request by colin-tso**
Update dynamic-theme-fixes.config to fix logo on *.abc.net.au, by removing existing svg path fill to make darkreader inversion work.

### CODE REVIEW

**Comment by Myshor** [comment]
Can you share some example URL? Because I think it could be fixed with IGNORE INLINE STYLE not that CSS

and as I went through some pages on abc.net.au I can not find anything with `data-component="ABCLogo"` in the html code.

**Comment by colin-tso** [comment]
image
This is on the main page ([www.abc.net.au](url)) and is on the "Masthead" for most pages.
I think instead I can use` INVERT` - for some reason I did not think of this
I had tried `IGNORE INLINE STYLE` which did not work.

**Comment by colin-tso** [comment]
Below seems to address the intent of the fix better.

```
*.abc.net.au

INVERT
[data-component="ABCLogo"] > path
[data-component="ABCNewsLogo"] > path
*.abc.net.au/emergency
```

Will put in additional commits if happy to proceed.

**Comment by Myshor** [comment]
As you started this PR I will give you the code what I should prefer. 😉
```
*.abc.net.au

IGNORE INLINE STYLE
[data-component="ABCLogo"] *

================================


```

Tested it and it works fine.

**Pull request merged**
