### PR TITLE
Next week updates.

### PR DESCRIPTION
**Pull request by Myshor**
Polar logo invert from dark one (not visible) to inverted.

### CODE REVIEW

**Comment by alexanderby** [comment]
Hi. Great work, thanks.

I decided to remove global `::placeholder` rule. While it can work for some websites, I'm afraid it can make it look worse for many others.

Could you please describe changes made for Facebook?

**Comment by Myshor** [comment]
Sorry for the delay. I had some trail run today and I'm just back home.

So... Summary for facebook: (most related to your page(s) and admin page for your page)
1. Dark promotion icon invert.
2. Link Info Circle fix. (dark i invert)
3. Share in Messenger icon fix. (dark invert)
4. album cogwheel invert
5. icon to add ads in admin page panel
6. Like icon not setting to white invert
7. Arrows to change pictures left right (if you have more pictures in post and can change them)
8. add commercial to your page dark icon in circle invert

the rest i was messing with ._3-8_ removed 'cause it was breaking all facebook banners on other sites. ;)

**Comment by alexanderby** [comment]
Thanks, there's no rush. I'll publish an update tomorrow.

If you have a fix for a popular website (like Facebook, YouTube etc), let's create a separate Pull Request for it.

**Comment by Myshor** [comment]
I had the same idea about separate branches for different sites fixes after this week. ;) I will do it like you mentioned.

**Pull request merged**
