### PR TITLE
Fix for icloud.com

### PR DESCRIPTION
**Pull request by rakleed**
- Invert logos.

### CODE REVIEW

**Review by akirataguchi115 — CHANGES_REQUESTED** [review]
I think you could just say
`.icloud-logo`
also these would be a nice addition
```
.tags-cloud-toggle
.tt-input-field
.network-badge-symbol
```

**Comment by akirataguchi115** [comment]
In the meantime I also tried to ask Apple Developers why they decided to implement the center parts with canvas instead of editable text: https://developer.apple.com/forums/thread/722684

**Comment by rakleed** [comment]
@akirataguchi115 when using the `.icloud-logo` selector, the Apple icon is not inverted on the main [icloud.com](https://www.icloud.com/), and it will no longer be possible to make a working rule for it that would not break inverting on pages with Notes, Disk, etc.

> also these would be a nice addition
> 
> ```
> .tags-cloud-toggle
> .tt-input-field
> .network-badge-symbol
> ```

I didn't find where you got those selectors from. Maybe it's better to do a separate PR for them?

**Comment by akirataguchi115** [comment]
I'll test your first note about .icloud-logo as soon as I can!

Also yeah sure I guess I'll do a separate PR for the three other selectors. Thanks for letting me know!

**Review by akirataguchi115 — APPROVED** [review]
Works as intended.

**Review by Gusted — APPROVED** [review]
Thanks!

**Pull request merged**
