### PR TITLE
Color inversions for 'move' menu elements

### PR DESCRIPTION
**Pull request by blameitonjoe**
When clicking the move icon (between the star and cloud icons) at the top, a small menu window ui lets you choose the destination. Some of the following icon elements were not inverted and I'm adding them to INVERT:
- Open folder in new window
- Window closing "x"
- Create new folder
- Select folder right chevron (hover)
- Shared with me (at root)
- Starred (at root)

Also added to CSS a bright color for the scrollbar thumb for this little window.

### CODE REVIEW

**Review by Gusted — COMMENTED** [review]
I think we can re-use the fix from `drive.google.com/picker`.

```CSS
INVERT
div[role="menu"] div[role="menuitem"]:not([class*=" "]) > div > div > div
div[role="button"][tabindex="0"]

CSS
div[role="menu"] div[role="menuitem"][class*=" "] > div > div > div,
div[role="button"][aria-disabled="true"] > div {
    filter: invert(50%) !important;
}

IGNORE INLINE STYLE
svg[class=""]
svg[class=""] *
```
Which does an good job on it while maintaining not to rely on obscure CSS Selectors.

**Comment by blameitonjoe** [comment]
Absolutely, @Gusted. This was my first ever contribution and tried to help on something that might benefit drive users. Sorry to waste your time.

**Comment by rakleed** [comment]
@Gusted can I just remove the rules separately for `drive.google.com/picker` and add them to `drive.google.com`?

**Comment by Gusted** [comment]
> can I just remove the rules separately for `drive.google.com/picker` and add them to `drive.google.com`?

I'm pretty sure I've set it to `/picker` for a reason, because due to conflicting CSS selectors. But give it a try and make sure you don't break anything, have a special note for the context menu's that you get when you right click on files/folders etc.

**Comment by rakleed** [comment]
The rule `INVERT div[role="button"][tabindex="0"]` breaks a lot. If I change it to `INVERT div[role="dialog"] div[role="button"][tabindex="0"]`, then everything will be displayed normally in the main interface, but for some reason it will stop working on https://drive.google.com/file. Also, if I add the rules `IGNORE INLINE STYLE svg[class=""]`, and `IGNORE INLINE STYLE svg[class=""] *` at the same time, they will also break the file properties icon in the main interface.

And in general, I did not understand what the rules are for `INVERT div[role="menu"] div[role="menuitem"]:not([class*=" "]) > div > div > div`, `IGNORE INLINE STYLE svg[class=""]`, `IGNORE INLINE STYLE svg[class=""] *`, so if I add the rules `INVERT div[role="dialog"] div[role="button"][tabindex="0"]`, `CSS div[role="menu"] div[role="menuitem"][class*=" "] > div > div > div, div[role="button"][aria-disabled="true"] > div { filter: invert(50%) !important; }` for https://drive.google.com, and do not touch the rules for https://drive.google.com/picker, then everything will be displayed correctly.

**Comment by Gusted** [comment]
Rakleed fixed this one with #5835

**Pull request closed without merging**
