### PR TITLE
Fixed tutorialspoint.com

### PR DESCRIPTION
**Pull request by Mertyn**
I fixed some inversion issues on the homepage and learning pages of [tutorialspoint.com](https://tutorialspoint.com/).
There are more pages of the site, that need fixing but this is all I got done so far.

tutorialspoint1

tutorialspoint2

### CODE REVIEW

**Comment by Mertyn** [comment]
I don't really understand why the test failed, I did everything exactly as it should be :(

**Comment by Gusted** [comment]
The fix should be above `tv.yandex.*`

**Comment by Mertyn** [comment]
Oh okay

**Comment by Gusted** [comment]
> The darkreader devtools put that there though. So maybe there is an issue there.

No, the `tv.yandex` isn't currently in the devtools as it was recently added.

**Comment by Mertyn** [comment]
> No, the `tv.yandex` isn't currently in the devtools as it was recently added.

Got it :)

**Comment by Gusted** [comment]
> Is there a tool or something you can recommend, that automatically inserts it in the right spot of the config file?

Devtools itself, I test every change locally so most of the new sites are alreaedy in my devtool.

**Comment by Mertyn** [comment]
> Devtools itself, I test every change locally so most of the new sites are alreaedy in my devtool.

Okay, well I'm just fixing it in my browser and then copy the changes over to the config file in the repo. So maybe I gotta improve my way of working with that, so that i always have the most recent config :D

**Pull request merged**
