### PR TITLE
blogs.windows.com

### PR DESCRIPTION
**Pull request by sprinkledcheese**
- Logo

### CODE REVIEW

**Comment by sprinkledcheese** [comment]
--darkreader-neutral-background doesn't work since it inherits from the background. Only solution for ms logo is white background.

**Comment by Gusted** [comment]
It the value that is used to set the background do the background color will automatically be updated when the user have a custom background color

**Comment by Gusted** [comment]
Btw do you use stock darkreader if so the variables aren't implemented yet for it.

**Comment by sprinkledcheese** [comment]
I'm on master build.

**Comment by Gusted** [comment]
Than the variable should work and dynamically update to the correct background.

**Comment by sprinkledcheese** [comment]
It just inherits the background color which the user has set, right? If I have dark background the logo will be just like before.

**Comment by sprinkledcheese** [comment]
It should look like this: chrome_nEJslYoNXa

**Comment by Gusted** [comment]
:/ it's tricky with Microsoft. Having background will improve visibility but makes it bit messy to have a random white background their.

**Comment by sprinkledcheese** [comment]
Shouldn't the variable work only for background's that should be darker instead of light. I don't see any other use case.

**Comment by sprinkledcheese** [comment]
If one uses ${} it messes in the other mode. If colour is used without ${}, the other mode doesn't have any issues.

**Comment by Gusted** [comment]
My idea was generally for people with custom themes and certain fixes that the background color of those fixes are dark or white or whatever and don't fit into the custom background color. That was my thoughts with implementating it.

**Comment by sprinkledcheese** [comment]
Ah nice. But for certain logos there should an exception.

**Comment by alexanderby** [comment]
Try putting this selector into `INVERT` section

**Comment by alexanderby** [comment]
...wait, it had to be `background: ${white} !important;`

**Comment by sprinkledcheese** [comment]
transparent doesn't work. ${white} works in both modes, ${black} makes the logo black in light mode. In light mode the colour is inverted from the dark mode, is that expected behaviour. Shouldn't it just invert colour regardless of mode?

**Pull request merged**
