### PR TITLE
Use correct Sync-Style

### LINKED ISSUE #3411: [Broken Website] onedrive
**Website**
https://onedrive.live.com/?id=22FB491072D6A964!225&cid=22FB491072D6A964

**How to Reproduce**
An example of this is
> 1. Go to a onedrive file page
> 2. The menubar is blinking

**Screenshots**
sshot-005
sshot-006

**System info:**
 - OS: Windows 10
 - Browser: Firefox
 - Darkreader Version: 4.9.16
 
**Additional context**
Disable and re-enable dark reader, the problem will disappear.

### LINKED ISSUE #3456: [BUG] [ESPN & such] White backgrounds in certain areas/banners
### **Describe the bug**

Some sites like ESPN (ESPN as best example,there's dozen more) have some weird "glitches" when using dark theme. 
At first (not always) it works fine but when you close the tab and re-open it again or have 3-4 more tabs to follow/compare games,it doesn't apply the whole dark theme. Even if you use it on the same tab and you go BACK and re-enter the box score tab,it still stays broken. 

It's mixed with coloring on the team names and you can't even see player's numbers/names either. 
I'll post pictures below from both scenarios. It happens on some websites but most common one I use and notice it consistantly is ESPN. 

### **Steps to reproduce**

- Go to: ESPN.com
- Click on: Any game score box and try going back and re-opening it or have it in mutliple tabs

### **Expected behavior**

To have the originally applied theme when whitelisting and removing it from whitelist which looks like [pic2] and be consistantly just like that

### **Actual behavior**

Bugs out after re-opening the tab/opening mutliple

### **Screenshots**

[pic1] image

[pic2] image (1)

### **System Information:**
 - OS: Windows 10 Pro x64 1909 Build
 - Browser: Brave 1.11.101 * Chrome 84.0.4147.125 * Edge 84.0.552.61 (Happens on all browsers pretty consistantly)
 - Dark Reader version: 4.9.16

### PR DESCRIPTION
**Pull request by Gusted**
- Get the correct sync style of your manage element and not someone else's element
- Resolves #3411
- Resolves #3456

### CODE REVIEW

**Review by alexanderby — APPROVED** [review]

**Comment by NRN1337** [comment]
Has been this updated? If so,version?

**Comment by Gusted** [comment]
> Has been this updated? If so,version?

Version 4.9.20 and above. Contains this fix.

**Comment by NRN1337** [comment]
I'm using 4.9.21 and issue is still there unfortunately.

**Comment by Gusted** [comment]
> I'm using 4.9.21 and issue is still there unfortunately.

Open up a new issue and fill out the necessary details, so I can have a look at it.

**Comment by NRN1337** [comment]
@Gusted Done ( #3769 ). I appreciate your time and effort

**Pull request merged**
