### PR TITLE
Improvements to dropbox.com

### PR DESCRIPTION
**Pull request by ceiphr**
Dropbox doesn't look terrible with Dark Reader enabled, but it could look better:

Old Dropbox Homepage
Old Dropbox All Files
---

This PR makes quite a few tweaks to Dropbox's CSS since their web offering styles different elements inconsistently.

The most obvious changes are for SVG icons, tables and buttons as seen below:

New Dropbox Homepage
New Dropbox All Files

Besides the changes seen in the images, here is a list of all significant stylings:
- Graphics with poor contrast were inverted
- Toggles, checkboxes, and buttons use light blue
- The side navigation is darker
- Table backgrounds are lighter
- Tab backgrounds are lighter
- Footer matches the background

Please let me know if there is anything I should change. Thank you.

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @ceiphr!

We have [dynamic styling](https://darkreader.org/blog/v4-9/) to change the `base colors` and that can make this lighter/darker and it shouldn't be forced to a fixed color trough a fix. As it seems to be that this fix mainly focusing on doing that.

Regards,
Gusted

**Comment by ceiphr** [comment]
@Gusted Is there a way I can improve this PR to get the same effect without leveraging fixed colors?

**Comment by Gusted** [comment]
> @Gusted Is there a way I can improve this PR to get the same effect without leveraging fixed colors?

Removing the CSS part, the INVERT section LGTM.

**Comment by ceiphr** [comment]
@Gusted One last question. I just committed the change you suggested to my branch and merged one new upstream commit.

Do I create a new PR for this branch? I'm asking, so I don't accidentally make any duplicates.

Thank you for all the help getting started with this project. I really appreciate it.

**Comment by Gusted** [comment]
> Do I create a new PR for this branch? I'm asking, so I don't accidentally make any duplicates

Yes, it's the best to create a new PR for this by 
https://github.com/darkreader/darkreader/compare/master...ceiphr:improved-dropbox.com?expand=1

**Pull request closed without merging**
