### PR TITLE
Fix for mail.qq.com

### PR DESCRIPTION
**Pull request by felixonmars**
Invert logo

### CODE REVIEW

**Comment by Myshor** [comment]
Can you share screens with before/after fix? Opening mail.qq.com without any account and loggin in doesn't give me any tip what you want to invert.

**Comment by felixonmars** [comment]
Sure.

Before:
image

After:
image

**Comment by Myshor** [comment]
but that will give inconsistency with logo on login page:
obraz

**Comment by felixonmars** [comment]
Indeed. Updated :)

**Pull request merged**
