### PR TITLE
Wikipedia formula fallback fix

### PR DESCRIPTION
**Pull request by erkinalp**
This one-line change fixes the math formula fallback images.

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @erkinalp!

Could you provide a example URL?

Regards,
Gusted

**Comment by erkinalp** [comment]
Any maths article, for example, https://en.wikipedia.org/wiki/Normal_distribution .

**Comment by Gusted** [comment]
This made all math things black?

**Comment by erkinalp** [comment]
Try again.

**Comment by Gusted** [comment]
I'm not seeing any changes.

**Comment by erkinalp** [comment]
Interestingly works for me.
resim

**Comment by Gusted** [comment]
Are you on invert? Or have any custom settings?

**Comment by erkinalp** [comment]
Yes, I have also changed the base colours of both the extension and the browser itself to light on dark (some sites are not darkened at all if I do not change the base colours using the browser preferences). Also changed the selection colour on the extension as well.

**Comment by Gusted** [comment]
> I am on dynamic, I have also changed the base colours of both the extension and the browser itself to light on dark (some sites are not darkened at all if I do not change the base colours using the browser preferences). Also changed the selection colour on the extension as well.

Okay as majority of the people are on default settings all fixes should be according to the default settings.

**Comment by erkinalp** [comment]
Do you plan adding a supplemental configuration file for keeping the local fixes separately? Because anyone on high contrast schemes will have similar problems with those fixes.
Can you also share a screenshot for the pre-PR situation?

**Comment by Gusted** [comment]
`.mwe-math-element` is already inverting all math formula's.

> Do you plan adding a supplemental configuration file for keeping the local fixes separately? Because anyone on high contrast schemes will have similar problems with those fixes.

We are planning to add a `User CSS` to separate user fixes for situations like this, but for now I recommend a extension like Stylus. 
It won't be added soon(as V5 roadmap don't contain this feature), but there are plans about it.

**Comment by erkinalp** [comment]
This is the fixup snippet for dark reader users with high contrast and dark browser base colour:
```CSS
@-moz-document domain("wikipedia.org") {
  .mw-body img.mwe-math-fallback-image-display,
  .mw-body img.mwe-math-fallback-image-inline {
    filter: invert(100%);
    border: none;
  }
}
```

**Pull request closed without merging**
