### PR TITLE
Add Polish i18n

### PR DESCRIPTION
**Pull request by rail01**
This PR adds Polish locales file to locales directory.

### CODE REVIEW

**Comment by rail01** [comment]
Thank you very much

**Comment by alexanderby** [comment]
Hi @rail01, could you please shorten some phrases?

The design is going to be changed, but currently there is not enough space for labels in short buttons.

Screen Shot 2020-01-16 at 10 47 11
Screen Shot 2020-01-16 at 10 47 24
Screen Shot 2020-01-16 at 10 47 43

**Comment by alexanderby** [comment]
There is no tool to check the new text without modifying the source code, but you can:
1. Right-click the label in popup, click **Inspect**.
2. Double click the text between `<span class="x">Text</span>`, edit and press Enter.

**Comment by alexanderby** [comment]
I've shortened some phrases as I could with my Polish knowledge https://github.com/darkreader/darkreader/commit/2c1ef30d6a97da6ce9c9a7167a08513e6eb3df8e

**Comment by rail01** [comment]
You've shortened them correctly - thanks.

**Pull request merged**
