### PR TITLE
Use RAF when proxy script blocked by CSP

### PR DESCRIPTION
**Pull request by alexanderby**

### CODE REVIEW

**Comment by Gusted** [comment]
This Resolves #4236

**Comment by alexanderby** [comment]
Oh, yes, I don't know why there's no CSP error in Chrome.

**Comment by Gusted** [comment]
I have a such feeling it might be disabled by default to show. Also uBlock origin has an option to hide CSP messages, you might have this option enabled?

**Comment by alexanderby** [comment]
I don't know how it works.

**Pull request merged**
