### PR TITLE
Add anilist.co to dynamic-theme-fixes.config

### PR DESCRIPTION
**Pull request by mgziminsky**
Use the sites dark theme as default

Copied the variable values for the sites native dark theme, which isn't the default theme for the site.

### CODE REVIEW

**Comment by alexanderby** [comment]
Did you try it in Dev Tools? `39,44,56` is not a valid CSS color, but `rgb(39, 44, 56)` is. Also you could use `${LightColor}` template so that brightness and contrast would be applied to color and it will be bright in light mode. But if you find this case rare and too tricky, you can leave dark colors.

**Comment by mgziminsky** [comment]
I did try it. The site uses variables to define its theme colors, and those are valid variable definitions. I didn't come up with these rules, they are directly from the sites own stylesheet. The site just doesn't use the dark theme by default

**Comment by alexanderby** [comment]
Great, I'm not sure if `!important` could be used with CSS variables, but if you say it works, then let it be.

**Comment by mgziminsky** [comment]
Yeah, I don't actually know for sure about the !important, but it doesn't break anything so I thought I might as well add it.

**Pull request merged**
