### PR TITLE
Fix for mail.qq.com

### LINKED ISSUE #5026: [Broken Website] mail.qq.com
# Broken Website

## Website

mail.qq.com
## How to Reproduce

- Open this site
- Login your account
## Expected behavior

The left and bottom should be black.
## Actual behavior

They're not black.
## Screenshots

image

## System Information

- OS: Windows
- Browser: Microsoft Edge 88.0.705.63
- Dark Reader Version: 4.9.27

### PR DESCRIPTION
**Pull request by Gusted**
- Resolves #5026 

Thanks to @shenzhiming88

### CODE REVIEW

**Comment by Gusted** [comment]
@shenzhiming88 Could you try out this fix, I've covered most parts. With little minor parts being intentionally left out as they part of an background-image which is hard to fix without breaking the site apart.

**Comment by shenzhiming88** [comment]
@Gusted Hello!
Thank you very much for the fix, but there are still some questions
After changing some skins, the page may have problems (e.g. ink shadow)
The input box for writing a letter is still white
image
image

**Comment by Gusted** [comment]
Ill stay with the default theme for now, as if I fix 1 theme Ill break the other one as they cannot be distinguish from each other at certain points. Especially the leftPanel.

**Comment by shenzhiming88** [comment]
@Gusted Hello!
Actually, the default theme is the `默认皮肤` which is blue and located on the far left instead of the one I use which is green.
For a more detailed check, I will do it tomorrow
Thank you

**Comment by shenzhiming88** [comment]
@Gusted Hello!
I still found some problems.
1. the edit box of the main text still seems to be white, still not fixed
image
2. some text is still not clearly visible (e.g. when the email is selected)
image

**Comment by Gusted** [comment]
The 2 issues should be fixed now, The editor can give weird results every reload which is something I hadn't seen before.

**Comment by shenzhiming88** [comment]
@Gusted 
Hello!
Thank you, but there are still some small problems
Some text color problems, for example, in "Settings(`设置`)", the text of the selected option above is not visible
image
And editor can't be fixed?
Thank you again!

**Comment by Gusted** [comment]
> And editor can't be fixed?

Partially, sometimes it works and the other time it has it's own will.

**Comment by shenzhiming88** [comment]
@Gusted 
Hello!
And the contents of the "file transfer station(`文件中转站`)" are not fixed
image

**Comment by shenzhiming88** [comment]
> > And editor can't be fixed?
> 
> Partially, sometimes it works and the other time it has it's own will.

This is strange ...... I tried a dozen times and the result was that the edit box was black at first and then quickly changed to white

**Comment by Gusted** [comment]
> @Gusted
> Hello!
> And the contents of the "file transfer station(`文件中转站`)" are not fixed
> image
> Thanks

Not reproducing.

And the editor doesn't show any white for me, for a while.

The current code is the best I can do, anything on top of this is just quirks and hacks and you will be better of using the `Filter` mode.

**Comment by shenzhiming88** [comment]
@Gusted I think it would be better to delete these codes
```
.settingSub a {
    color: ${#4d5d2c} !important;
}
```
image
Thank you

**Comment by shenzhiming88** [comment]
@Gusted

**Pull request merged**
