### PR TITLE
Improve Viet Nam translation

### PR DESCRIPTION
**Pull request by NguyenASang**

### CODE REVIEW

**Comment by NguyenASang** [comment]
Is this translate too long ? I will try to shorten the word

**Comment by Gusted** [comment]
> Is this translate too long ? I will try to shorten the word

Quick reply: seems like the initial email got in spam(had again some filter issues). Will have a look once I cleared my other emails ;)

**Review by Gusted — APPROVED** [review]
LGTM.

**Comment by NguyenASang** [comment]
How do I test my language interface? I want to optimize it for better fit.

**Comment by Gusted** [comment]
> How do I test my language interface? I want to optimize it for better fit.

You will have to build the master branch.
This is the current one:
[release.tar.gz](https://github.com/darkreader/darkreader/files/7283445/release.tar.gz)

**Pull request merged**
