### PR TITLE
Update dynamic-theme-fixes.config

### PR DESCRIPTION
**Pull request by frogtd**
This fixes the issue where the unread icon is very hard to see (both on channels and on servers).

### CODE REVIEW

**Comment by Gusted** [comment]
Hi!

Maybe you saw it for yourself but Discord classes are unpersistent and pretty much reused in ways so I had a little play around the HTML structure(1 big mess) and came up with the following to cover all situations and changed to dynamic variables
```css
div[aria-label="Servers"][role="tree"] > div[class^="listItem"] > div[class^="pill"][class*="wrapper"] > span[class^="item"],
div[class^="tutorialContainer"] > div[class^="listItem"] > div[class^="pill"][class*="wrapper"] > span[class^="item"],
div[class^="scroller"][class*="scrollerBase"] > div > div[class^="listItem"] > div[class^="pill"][class*="wrapper"] > span[class^="item"] {
    background-color: var(--darkreader-neutral-text) !important;
}
```

You can change it to this CSS code.

Regards,
Gusted

**Comment by frogtd** [comment]
That css still has the unread icon to be black, and its on a dark gray background so its almost impossible to see.

**Comment by Gusted** [comment]
What do you mean by unread icon?

**Comment by frogtd** [comment]
image
this white dot

**Comment by Gusted** [comment]
```css
div[aria-label="Servers"][role="tree"] > div[class^="listItem"] > div[class^="pill"][class*="wrapper"] > span[class^="item"],
div[class^="tutorialContainer"] > div[class^="listItem"] > div[class^="pill"][class*="wrapper"] > span[class^="item"],
div[class^="scroller"][class*="scrollerBase"] > div > div[class^="listItem"] > div[class^="pill"][class*="wrapper"] > span[class^="item"],
div[class^="scroller"][class*="scrollerBase"] > div[class^="listContent"] > div[class^="containerDefault"] > div[class*="modeUnread"] > div[class^="unread"] {
    background-color: var(--darkreader-neutral-text) !important;
}

**Comment by frogtd** [comment]
That doesn't work when the server is inside a folder.

**Comment by Gusted** [comment]
```css
div[class^="pill"][class*="wrapper"] > span[class^="item"],
div[class*="modeUnread"] > div[class^="unread"] {
    background-color: var(--darkreader-neutral-text) !important;
}
```
Does this work for folders?

**Comment by gabriele2000** [comment]
> 
> 
> ```css
> div[class^="pill"][class*="wrapper"] > span[class^="item"],
> div[class*="modeUnread"] > div[class^="unread"] {
>     background-color: var(--darkreader-neutral-text) !important;
> }
> ```
> 
> Does this work for folders?

Like this?
immagine
immagine

**Comment by Gusted** [comment]
> Like this?
> immagine
> immagine

Yes and it LGTM.

**Pull request merged**
