### PR TITLE
Fix for e-katalog.ru

### PR DESCRIPTION
**Pull request by boingo-00**

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @boingo-00!

Where can I find the fixed elements?

Regards,
Gusted

**Comment by boingo-00** [comment]
изображение
Pop-up in right filter in any category

**Comment by Gusted** [comment]
Hi @boingo-00!

Which filter do you hover?
I only see `id:` and then some number

image

Regards,
Gusted

**Comment by boingo-00** [comment]
Click on any checkbox

**Comment by Gusted** [comment]
Aha, I see. So why the change of colors?

**Comment by boingo-00** [comment]
Because original colors is too bright and text is impossible to read

**Comment by Gusted** [comment]
Hmm, I will disagree with you on that. The provided fix for me is actually the one to impossible to read for me.
The modified colors by Dark Reader on default settings is on a good dark-ish color with a white-ish text color and a good contrast-ration.

Regards,
Gusted

**Comment by boingo-00** [comment]
Oh, sorry, default is much better
My fix is old enough

**Pull request closed without merging**
