### PR TITLE
Added discord.com pages

### PR DESCRIPTION
**Pull request by sprinkledcheese**

### CODE REVIEW

**Comment by sprinkledcheese** [comment]
Examples:
/developers subpage: https://discord.com/developers/docs/intro
/invite subpage: https://discord.com/invite/hTKzmak

**Comment by Gusted** [comment]
Not sure we have a open PR for subdomains #2517

**Comment by sprinkledcheese** [comment]
This PR is more subtle, currently whole domain is under global dark list. Also using this subpages you woudn't need to add blog.discord.com and support.discord.com

**Comment by KaKi87** [comment]
Hello,
Since this change, Dark Reader is not disabled when opening Discord by clicking "Open Discord" at https://discord.com/.
Thanks

**Pull request merged**
