### PR TITLE
Fix for yscec.yonsei.ac.kr

### PR DESCRIPTION
**Pull request by snoop2head**
### Dark Reader on Current version
Screen Shot 2020-09-02 at 12 51 50 PM

### Dark Reader on PR version
Screen Shot 2020-09-02 at 12 52 15 PM

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @snoop2head!

As this content is only available to students, I unfortunate can't see the fixes for myself.
So the side-bar is obvious, however the iframe what is inside the iframe, just some text for assignments. As Iframes can be used for a lot of things and could contain pictures/images(Not sure if this is the case) and they will be inverted as well.

Regards,
Gusted

**Comment by snoop2head** [comment]
Thanks for the quick reply @Gusted!

The purpose was to make lecture videos on white background to become dark.
For me and other students like #779, inverting the colors of video is favorable.

Korean undergraduate students' consensus is that they are having sore eyes from watching white background videos for 20hrs/week. This is due to the social status to hold lectures online only, part of social distancing policy of the government.

As you have mentioned, iframe can be used for pop-up, images, video etc. 

However, yscec.yonsei.ac.kr uses iframe as providing video contents only. The website's iframe tag doesn't even have id or class name, since it is only used for video. Videos on website use iframe, whereas other medias are provided in form of downloadable file. There's another student portal that utilizes iframe for multiple purposes, but yscec isn't the case.

I hope the PR makes it to the update, so the other students can benefit from it.

**Comment by Gusted** [comment]
> The purpose was to make lecture videos on white background to become dark.

I assume with lecture videos, just a power point presentation or something that way so that it's still visible to look at it.

**Comment by snoop2head** [comment]
@Gusted Precisely!

**Comment by Gusted** [comment]
Got ya, than I will merge it

**Pull request merged**
