### PR TITLE
Fixed weboas.is

### PR DESCRIPTION
**Pull request by sprinkledcheese**
Only the main page and forum is dark.

### CODE REVIEW

**Comment by Gusted** [comment]
Which subsite isn't dark?

**Comment by sprinkledcheese** [comment]
https://weboas.is/news/
https://weboas.is/tech/
https://weboas.is/crypto/
https://weboas.is/stocks/
etc.

**Comment by Gusted** [comment]
Let's than wait for this #2517 so you can use 
weboas.is
!weboas.is/news
etc.

**Comment by sprinkledcheese** [comment]
That's great change. But the number of pages in dark mode is significantly less, so consider adding the commits.

**Comment by sprinkledcheese** [comment]
Ok nvm there are subpages too which I didn't see earlier.

**Comment by sprinkledcheese** [comment]
For future use: weboas.is/convert/currency/
weboas.is/convert/crypto/
weboas.is/convert/unit2/
weboas.is/editors/editor/

**Comment by sprinkledcheese** [comment]
@Gusted

**Comment by Gusted** [comment]
Blocked due to #2517

**Comment by sprinkledcheese** [comment]
Ah, this took way long than I thought it would.

**Pull request closed without merging**
