### PR TITLE
Fixes for wikisource and baidu.com

### PR DESCRIPTION
**Pull request by Matr1x-101**
This fixes the logos for wikisource. It also fixes a video camera icon used on wikisource.

### CODE REVIEW

**Comment by Matr1x-101** [comment]
By the way, the most recent commit addresses #10223

**Comment by Matr1x-101** [comment]
@bershanskiy Could you please review this? Thanks.

**Comment by Matr1x-101** [comment]
@bershanskiy Could you please review this? Thanks.

**Comment by Matr1x-101** [comment]
@Gusted could you please review this? Thanks.

**Review by Gusted — APPROVED** [review]

**Pull request merged**
