### PR TITLE
Fixes for zoom joined page

### PR DESCRIPTION
**Pull request by Yash-Singh1**

### CODE REVIEW

**Comment by Gusted** [comment]
Hey @Yash-Singh1!

Do you have an before/after screenshot?

Regards,
Gusted

**Comment by Yash-Singh1** [comment]
@Gusted 

Here is the link: https://us04web.zoom.us/postattendee?id=4

Before:
Screenshot from 2020-12-06 20-55-22

After:
Screenshot from 2020-12-06 20-55-04


This page appears sometimes after joining a zoom meeting (I think it is randomized)

**Comment by Yash-Singh1** [comment]
There were some other postattendee pages so I will fix those then unconvert from draft

**Comment by Yash-Singh1** [comment]
All of the other pages use the same selectors.

**Pull request merged**
