### PR TITLE
Improved dropbox.com

### PR DESCRIPTION
**Pull request by ceiphr**
This PR inverts folder SVGs, file type SVGs and "empty page" graphics on dropbox.com to improve contrast.

Please see images below for examples of the changes:

> Search Before
> Search Before
> Search After
> Search After

> Document Preview Before
> Document Preview Before
> Document Preview After
> Document Preview After

> Homepage Recommendations Before
> Homepage Recommendations Before
> Homepage Recommendations After
> Homepage Recommendations After

> File Requests Before
> File Requests Before
> File Requests After
> File Requests After

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @ceiphr!
 
I've checked the fix and I'm not sure what changed.

Regards,
Gusted

**Comment by ceiphr** [comment]
Hey @Gusted 

I should have been more thorough with my PR write-up.
I've updated the PR with images to demonstrate the changes.
Let me know if anything else is needed. Thank you.

**Comment by Gusted** [comment]
Hi @ceiphr!

Did you had a look at `IGNORE INLINE STYLE`

I think it could be used on the folder SVG's so Dark Reader won't modify the colors and it will be reverted to the original colors.

**Comment by ceiphr** [comment]
Hey @Gusted 

That approach does seem nicer. I applied it to the `path` of the folder SVGs in 
1e8139f.

**Pull request merged**
