### PR TITLE
Update dynamic-theme-fixes.config

### PR DESCRIPTION
**Pull request by Antoine1673**
fix inversion issue on text in blocks at ai2.appinventor.mit.edu

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @Antoine1673!

What's the exact purpose of this fix? As doesn't seem to add any value to the existing colors and for me make it less readable
image

Regards,
Gusted

**Comment by Antoine1673** [comment]
Hello

That’s weird, on your screenshot the background doesn’t seem to be dark like mine.
Before the changes I made, it looked like this:
[cid:image001.png@01D6B3A2.6447CFB0]
For some light-colored blocks it was not easily readable, so I figured out that changing all block texts to black would be better. Here it is after my modification:
[cid:image004.png@01D6B3A2.6447CFB0]
I am using the default configuration of Dark Reader for this website.
If don’t know why it doesn’t look like this on your side, if you want me to send some config files or anything just tell me.

Regards

Antoine

De : Gusted <notifications@github.com>
Envoyé : jeudi 5 novembre 2020 18:21
À : darkreader/darkreader <darkreader@noreply.github.com>
Cc : Antoine1673 <angrimault@outlook.fr>; Mention <mention@noreply.github.com>
Objet : Re: [darkreader/darkreader] Update dynamic-theme-fixes.config (#4044)


Hi @Antoine1673<https://github.com/Antoine1673>!

What's the exact purpose of this fix? As doesn't seem to add any value to the existing colors and for me make it less readable
[image]<https://user-images.githubusercontent.com/25481501/98274305-895a9280-1f93-11eb-80dc-bd4861fbcfbd.png>

Regards,
Gusted

**Comment by Gusted** [comment]
> For some light-colored blocks it was not easily readable, so I figured out that changing all block texts to black would be better. Here it is after my modification:

In case of that some CSS is better to fix this.

```CSS
csselector {
    color: var(--darkreader-neutral-text) !important;
}
```

**Comment by Antoine1673** [comment]
Well, I indeed saw in the GitHub that the INVERT filter was mostly for wrongly inverted pictures, but I tried to use CSS and never got it to work, even by trying almost every selector and combination of these elements.
I’m not a CSS professional though, so maybe someone better than me would figure out how to do. If you or someone else could fix it I would greatly appreciate it.
Anyway, I understand my error, thank you for helping me.
Also, in my previous message the two screenshots showed two groups of blocks with different colors but in the not-inverted mode they are actually the same color. I think it is because the lighter group of blocks was made later and created after the filter is applied, but I don’t think it is displaying correctly.
Do you want me to report this as a bug?

Regards

Antoine

De : Gusted <notifications@github.com>
Envoyé : jeudi 5 novembre 2020 23:26
À : darkreader/darkreader <darkreader@noreply.github.com>
Cc : Antoine1673 <angrimault@outlook.fr>; Mention <mention@noreply.github.com>
Objet : Re: [darkreader/darkreader] Update dynamic-theme-fixes.config (#4044)


For some light-colored blocks it was not easily readable, so I figured out that changing all block texts to black would be better. Here it is after my modification:

In case of that some CSS is better to fix this.

csselector {

    color: var(--darkreader-neutral-text) !important;

}

**Comment by Gusted** [comment]
As far I understand your issue and seeing the CSS myself https://github.com/darkreader/darkreader/pull/4044/commits/7f7d2b7e5c0238098b5615cc712008a23455cc66 should do it. Maybe some rare cases with some weird backgrund-color contrast.

**Comment by Antoine1673** [comment]
I tried this exact code and it didn’t work.
My config is not updated yet but I tried to copy the same code and it isn’t working.
Is your modification working on your side?
Maybe our configs are not the same.

Regards

Antoine

De : Gusted <notifications@github.com>
Envoyé : vendredi 6 novembre 2020 09:52
À : darkreader/darkreader <darkreader@noreply.github.com>
Cc : Antoine1673 <angrimault@outlook.fr>; Mention <mention@noreply.github.com>
Objet : Re: [darkreader/darkreader] Update dynamic-theme-fixes.config (#4044)


As far I understand your issue and seeing the CSS myself 7f7d2b7<https://github.com/darkreader/darkreader/commit/7f7d2b7e5c0238098b5615cc712008a23455cc66> should do it. Maybe some rare cases with some weird backgrund-color contrast.

**Comment by Gusted** [comment]
> I tried this exact code and it didn’t work.
My config is not updated yet but I tried to copy the same code and it isn’t working.
Is your modification working on your side?
Maybe our configs are not the same.

It's working for me, do you have the latest version of Dark Reader(4.9.22/4.9.23)? I'm using the default config.

**Comment by Antoine1673** [comment]
I’m on 4.9.23, and I didn’t change the config for this website.

De : Gusted <notifications@github.com>
Envoyé : vendredi 6 novembre 2020 11:23
À : darkreader/darkreader <darkreader@noreply.github.com>
Cc : Antoine1673 <angrimault@outlook.fr>; Mention <mention@noreply.github.com>
Objet : Re: [darkreader/darkreader] Update dynamic-theme-fixes.config (#4044)


I tried this exact code and it didn’t work.
My config is not updated yet but I tried to copy the same code and it isn’t working.
Is your modification working on your side?
Maybe our configs are not the same.

It's working for me, do you have the latest version of Dark Reader(4.9.22/4.9.23)? I'm using the default config.

**Comment by Gusted** [comment]
What are the specific block where this is being caused? as most for works just fine.

**Comment by Antoine1673** [comment]
I didn’t observe an exact pattern, but it seems to be on the most recent blocks created way after the filter is applied.
I will use this website quite a bit this week, I will try to understand the exact behavior of this bug.

De : Gusted <notifications@github.com>
Envoyé : vendredi 6 novembre 2020 11:51
À : darkreader/darkreader <darkreader@noreply.github.com>
Cc : Antoine1673 <angrimault@outlook.fr>; Mention <mention@noreply.github.com>
Objet : Re: [darkreader/darkreader] Update dynamic-theme-fixes.config (#4044)


What are the specific block where this is being caused? as most for works just fine.

**Pull request merged**
