### PR TITLE
Fixes for reddit.com

### PR DESCRIPTION
**Pull request by Katzenwerfer**
These rules are for the site that Reddit serves when the user is not logged in.
Currently, I do not have an account, so I cannot test for problems on the regular site.

The changes should be well documented in the commit messages.

I am still missing other fixes I want to add, so I will keep this as a draft for a bit.
After that, I will post some screenshots showing the changes in case maintainers are not able to test them correctly.

### CODE REVIEW

**Comment by alexanderby** [comment]
It looks that Dark Reader variables are not applied properly. Could you please share some screenshot so that I could try to figure out the problem?

**Review by mistressxalexis — APPROVED** [review]

**Comment by Katzenwerfer** [comment]
It is finished now.

The changes can be noticed in 

- [The home feed](https://www.reddit.com/?feed=home)
- [Any Reddit post](https://www.reddit.com/r/mildlyinfuriating/comments/18z48bc/personalized_gift_for_iva/)
- [Search without subreddit](https://www.reddit.com/search/?q=foobar)

I will attach some screenshots that show the changes.

<details>
<summary>Trending posts in the home feed</summary>

The screenshot does not show it, but I am hovering over the element.
image
image

</details>

<details>
<summary>Some buttons in the page</summary>

The screenshot does not show it, but I am hovering over the element.
image
image

</details>

<details>
<summary>Results in a search without subreddit</summary>

The screenshot does not show it, but I am hovering over the element.
image
image

</details>

<details>
<summary>Related communities in a search without subreddit</summary>

The screenshot does not show it, but I am hovering over the element.
image
image

</details>

<details>
<summary>Trailing threadlines in the comment tree of comments</summary>

image
image

</details>

<details>
<summary>Subreddit and user hovercards</summary>

image
image


</details>

<details>
<summary>The Reddit logo</summary>

image
image

</details>

There are some changes to text color I did not take a screenshot of, but they are basically corrections for hovering elements and using the correct dark reader variables in some cases.

**Comment by Katzenwerfer** [comment]
Again, since I don't have a Reddit account, I can't check for myself if the changes affect anything on the regular site, so I would recommend having someone with an account check it out.

**Comment by Katzenwerfer** [comment]
> It looks that Dark Reader variables are not applied properly. Could you please share some screenshot so that I could try to figure out the problem?

Sorry for not paying attention to your comment earlier @alexanderby 
I am unsure if the screenshots would be enough to track down that problem with the vars.
Worth mentioning that on my end, I never found any issues with them.

**Comment by Myshor** [comment]
OK... I'm merging. We have already some issues with Reddit open - maybe it will fix most of them. :)

**Pull request merged**
