### PR TITLE
SteamTimeIdler.com is dark

### PR DESCRIPTION
**Pull request by Committing**
I've written an addendum to the config file with my site

Kindest regards

### CODE REVIEW

**Comment by Gusted** [comment]
Interesting site!

Also could you make the searchbar on https://steamtimeidler.com/support/faq/ a dark color?

Thank you for contributing to Darkreader!

**Comment by Committing** [comment]
Thank you @Gusted ! I have just pushed an update for the FAQ search input field.

I do have a couple other white inputs which I'll change over soon.

I hope this is sufficient 

Thank you kindly

Jack

**Comment by Gusted** [comment]
Hey Jack,

Thank you for updating it. I always like if the site is everywhere black like every other darkreader user. This gonna gonna be merged soon when the owner have time!

**Comment by Gusted** [comment]
Seems like I got write permissions So here you go!

**Comment by Committing** [comment]
Hey, thanks so much @Gusted  !

**Pull request merged**
