### PR TITLE
fixed a lot on mydealz.de

### PR DESCRIPTION
**Pull request by Progaros**

### CODE REVIEW

**Comment by Progaros** [comment]
This needs to be added to mydealz.de

```
INVERT
.cept-thread-image-link
.cept-thread-image-clickout
```

but my previous changes didn't make it in the original file
how can I add this now?

**Comment by Progaros** [comment]
thanks

when will this be added globaly?

**Comment by risualiser** [comment]
Sorry, I'm not a developer, wait for alexanderby.

**Comment by Progaros** [comment]
so you only reviewed my changes and alexanderby accepts it later?
sorry, I'm pretty new to github

**Comment by risualiser** [comment]
Yeah, I really like to help with it and watch the progress of project.
Maybe someday I learn TypeScript and start to write modifications for this extension.

**Comment by Progaros** [comment]
great
thanks

**Comment by alexanderby** [comment]
Thank you. Sorry for the delay.

**Comment by Progaros** [comment]
No problem, thank you for adding it permanently

Alexander Shutov <notifications@github.com> schrieb am Do., 6. Sep. 2018,
19:34:

**Pull request merged**
