### PR TITLE
Fix for Microsoft Edge Translate extension

### PR DESCRIPTION
**Pull request by AhmedElghrbawy**
- Fix wrong text color.

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @AhmedElghrbawy!

Could you share an link where I can download this extension?

Regards,
Gusted

**Comment by AhmedElghrbawy** [comment]
[Edge Translate](https://microsoftedge.microsoft.com/addons/detail/edge-translate/bfdogplmndidlpjfhoijckpakkdjkkil)

**Comment by Gusted** [comment]
Hi @AhmedElghrbawy!

I'm not sure, but it does show for me it's correctly and the texts gives me a white color.

Regards,
Gusted

**Comment by AhmedElghrbawy** [comment]
Hey @Gusted!

I tried setting everything back to default for both extensions to see if there is something wrong with my configuration, yet the problem still exists (at least for me).

Here is how to produce the problem:

* Select a word or a phrase, right click and translate that word.
* This works well for the first time you translate something, but for the following times **in the same Edge tab**, the translated text would be displayed in wrong colors (black text on black background).

Screenshot_3

Increasing the contrast as I always like to configure dark reader, would make the translated text unreadable at all.

If this displays correctly for you, then maybe there is something wrong with my setup making this is my own problem.



Thanks, and sorry for bothering.

**Review by Gusted — APPROVED** [review]
Ah I see! Thank you

**Pull request merged**
