### PR TITLE
fix for facebook.com

### PR DESCRIPTION
**Pull request by Myshor**
Live streams with enabled native fb dark mode fix.

Before:
image

After:
image

### CODE REVIEW

**Comment by Myshor** [comment]
Moved maps darkening into CSS - fixes white maps in native dark fb mode after last commit. 😄

**Comment by Myshor** [comment]
Inline for svg icons fix:
image

**Comment by Myshor** [comment]
Exclude some buttons for color fix to have it back white instead of gray.
Added force background image for maximize button instead of using blob.
image

**Comment by mrturkmen06** [comment]
I was planning to open an issue regarding to facebook.com, however I saw these improvements and would like to add one more issue. (I could not see before after photo of this particular issue in your comments that's why I called it as issue)
Likes pop-up window seems does not work very well. The names are not visible in dark mode. @Myshor. I thought that you can take this issue since you already done with other issues of facebook.com site. 

Btw, thank you very much for your contribution ! 

Screenshot 2020-05-18 at 20 51 22

**Comment by Myshor** [comment]
@mrturkmen06 You mean new facebook design? Cause I can not reproduce this on likes.
In new design I see:
image

On old design:
image

**Comment by mrturkmen06** [comment]
No I do not want to mean new design, the name and surname was not properly displayed when I click likes section as you can see from the SS that I shared. 
 It could be depended on browser @Myshor, I am using 76.0.1 (64-bit) Firefox. I guess, you are using chrome.

**Comment by Myshor** [comment]
If you can please create new issue with info that Firefox is used and with screen of your darkreader settings. I think I will merge this Pull Request today and I can forget to take a look in Firefox with all this fixes included. ;)

**Comment by mrturkmen06** [comment]
> If you can please create new issue with info that Firefox is used and with screen of your darkreader settings. I think I will merge this Pull Request today and I can forget to take a look in Firefox with all this fixes included. ;)
Got it 👍🏻 
Thanks

**Pull request merged**
