### PR TITLE
Fix resolving absolute paths for non-index pages

### PR DESCRIPTION
**Pull request by Gusted**
Related issue #1077

[Test-pages.zip](https://github.com/darkreader/darkreader/files/4497032/Test-pages.zip)
That's the test pages I've used.

As you know mostly if not all modern website don't have .html .htm .php after their pages as they use index.html or similar so when you request the url it was automaticly grab index.html for you etc.

But as for older websites they sometimes still use .html and .php for their sub domains sites. That can causes issues with loading images. As of like [this site](https://www.musl-libc.org/how.html) It's loads an image on  on the .listpanel (This screenshot was been made with this fix as you can see the background image).
As in the css of this sites it's sets the background-image to `    background-image: url(puzzle-a2.svg);` An incorrect way for modern browsers and HTML5 but back than an very normal way to load images. 

So darkreader will come to the image and spit back out that it absoluteURL is at `https://www.musl-libc.org/how.html` While this will be correct if how.html wasn't a file but a folder. 

With this Patch it will check if the last pathPart(not the image ofc) ends with .html .htm .php and splice this from the array as this isn't a real path/folder but a file. And it will check if the pottential .html .htm .php isn't a backwards indicator.

As of the test pages you will need to host it on a localhost 
That can be simply with python
`python -m http.server 1337` for Python 3 on windows
`python3 -m http.server 1337` for Python 3 on Linux distro's

You will find their some files and folders. I think you can figure yourself out to test this first without the fix and than with the fix and see that nonindex.html will as asked get the good url to load the image and in SomeFolder/FolderForBackwardsTest you will find the both files have ../ in the css to show it will detect automaticcly if the potetional is a backwards indicator.

Regards,
Your new member Gusted

### CODE REVIEW

**Comment by Gusted** [comment]
Approved the unit test and the Simplifer looks good

**Comment by Gusted** [comment]
> I've simplified it a little bit and added some tests. Not sure if I understand how CSS files resolve paths correctly.

The current implemetation is Correct so if the test pass it should be a green light.

**Comment by alexanderby** [comment]
Need to find some doc how CSS resolves files paths.

**Comment by Gusted** [comment]
[CSS level-1](https://www.w3.org/TR/CSS1/#url)
[CSS level-2](https://www.w3.org/TR/CSS2/syndata.html#uri)
[CSS level-3](https://drafts.csswg.org/css-values-3/#urls)
[CSS level-4](https://drafts.csswg.org/css-values-4/#urls)

**Pull request merged**
