### PR TITLE
Fix for icloud.com

### LINKED ISSUE #9268: [Broken Website] icloud.com/reminders white foreground on black background(see pictures)
# Broken Website Report

## Website Address

icloud.com/reminders
icloud.com/notes
icloud.com
## Steps To Reproduce

- Go to icloud.com/reminders
- go to any reminder or create a new one
- white foreground on black background

## Problematic Observation

it should be switched to dark theme, as their native app on iphone/ipad.
## Screenshots

broken reminders website
image
broken notes website
image

## System Information

- OS:  windows 11 latest
- Browser:  chrome version: Version 103.0.5060.114 (Official Build) (64-bit)
- Dark Reader Version: 4.9.5.2 latest

## Additional Context

also icloud.com/notes have the same problem, so i think icloud.com needs to be fixed as a whole.

### PR DESCRIPTION
**Pull request by c-nagy**
- Invert loading spinner
- Invert Notes editor
- Invert dark iCloud logo in Reminders
- Remove bright background images from Notes and Reminders panels
- Resolves #9268

### CODE REVIEW

**Review by Gusted — APPROVED** [review]
Many thanks for looking into the issue.

**Comment by yazan1107** [comment]
man for real i am the one who posted this issue, first time getting someone solving my problem such a nice feeling thanks mate! when will i see the update on my extension?

**Comment by c-nagy** [comment]
Thanks for the encouragement, glad I could help! @yazan1107 I'm not sure when the next update will be released with the latest fixes, but in Dark Reader if you go to "Dev tools > Preview new design" you can reopen the Dark Reader interface and go to "Settings > Manage site settings > Synchronize site settings" to sync all the new fixes from this repo automatically.

**Comment by yazan1107** [comment]
> Thanks for the encouragement, glad I could help! @yazan1107 I'm not sure when the next update will be released with the latest fixes, but in Dark Reader if you go to "Dev tools > Preview new design" you can reopen the Dark Reader interface and go to "Settings > Manage site settings > Synchronize site fixes" then go to "Dev tools > Reset changes > Apply" to sync all the new fixes from this repo.

tried this still experiencing white panels which is pretty deadly for my eyes at night!

**Review by yazan1107 — COMMENTED** [review]
very good

**Comment by c-nagy** [comment]
@yazan1107 That’s odd, maybe open the dev tools and make sure that this patch is showing up by searching for icloud.com and looking at the code block under it. You can paste in the changes if it’s not syncing for some reason.

**Comment by yazan1107** [comment]
man i think the problem is with your code... did you fix the white foreground on black background when adding new note? i am still experiencing that...

**Comment by c-nagy** [comment]
@yazan1107 Can you send me a screenshot of the issue and the Dark Reader Dev Tools section for icloud.com? This is how it looks for me on Chrome v103.0.5060.114 Windows 11 Pro:

image

image

If I can reproduce the issue I can probably get a patch in to fix it right away.

**Comment by yazan1107** [comment]
> @yazan1107 Can you send me a screenshot of the problem and the Dark Reader Dev Tools section for icloud.com? This is how it looks for me on Chrome v103.0.5060.114 Windows 11 Pro:
> 
> image
> 
> image
> 
> If I can reproduce the issue I can probably get a patch in to fix it right away.

oh maybe it is because i am using windows? ok i am sending you everything you asked:)
image
image

**Comment by yazan1107** [comment]
btw the fix on icloud.com/notes worked just fine.

**Comment by c-nagy** [comment]
> why your reminders website is different than mine? i copied your merged code and pasted it to my dev tools

@yazan1107 Ah I think I figured it out. When Reminders are synced to an iOS device from iCloud it changes the web interface for some reason. I was able to reproduce the issue by syncing my device and I should be able to fix it now. Thanks for the info and screenshots, that helped a lot!

**Comment by yazan1107** [comment]
how can i sync it? i liked the view of yours.

**Comment by c-nagy** [comment]
@yazan1107 Could you test if this fixes the reminder and notes issues? Adding the following under INVERT in the code:
.rm-list-body
.note-list-item-attachment

**Comment by yazan1107** [comment]
> @yazan1107 Could you test if this fixes the reminder and notes issues? Adding the following under INVERT in the code: .rm-list-body .note-list-item-attachment

yes it worked
it has two different colors
image

**Comment by yazan1107** [comment]
you can check my reply now @c-nagy as i typed it correctly now.

**Comment by c-nagy** [comment]
@yazan1107 Hmm I see what you mean. Unfortunately that's tricky because it's contained in a <canvas> element and I think it's only possibility to invert the entire canvas element, and you can't select things inside it to selectively modify. I could be wrong about that though. Would you be okay with me merging the fixes so far and then you can open another Github issue for that problem?

**Pull request merged**
