### PR TITLE
Add license notice in generated CSS

### LINKED ISSUE #5628: [Feature Request] License for exported theme
# Feature Request

## Is your feature request related to a problem? Please describe

I'd like to add a dark theme to my personal website, and the CSS generated from Dark Reader (amazing extension BTW!) is a very good starting point (95% already there, I'd say). Unfortunately, there is no license attached when you export the theme, so I cannot in good faith include it in my website. 

## Describe the solution you'd like

Can we add a notice at the top of the file, with the license? I'd love it to be MIT, so I can integrate as long as I keep the notice, but any other free license should be good

### PR DESCRIPTION
**Pull request by Gusted**
- Resolves #5628

### CODE REVIEW

**Comment by Gusted** [comment]
Notices that Dark Reader had an hard time with extracting github's CSS so added some improvements as well.

**Review by lodenrogue — APPROVED** [review]

**Comment by Gusted** [comment]
@alexanderby Could you give a look at this PR?

**Review by alexanderby — APPROVED** [review]
Hey, it's holiday time!

**Comment by Gusted** [comment]
> Hey, it's holiday time!

Got back today. Had a great amount of sleep and energy to review some issues/PR's 😄

**Pull request merged**
