### PR TITLE
Added fix for build-electronic-circuits.com

### PR DESCRIPTION
**Pull request by AnthonyWritesBadCode**

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @AnthonyWritesBadCode!

Could you explain what this fix does?

Regards,
Gusted

**Review by AnthonyWritesBadCode — COMMENTED** [review]
Fixed a typo

**Comment by AnthonyWritesBadCode** [comment]
This fix inverts the background image, which was white, and changes the background color of the "todo lists" to have more contrast with the text color

**Comment by Gusted** [comment]
Do you have an example link where I can observe this behaviour?

**Comment by AnthonyWritesBadCode** [comment]
This is the page that I used:

https://www.build-electronic-circuits.com/kicad-tutorial/

**Pull request merged**
