### PR TITLE
Add swedish locale

### PR DESCRIPTION
**Pull request by august-norkko**
Added sv.config, swedish translation.

PR #1861 looks inactive, so here goes.

### CODE REVIEW

**Comment by alexanderby** [comment]
Hi @august-norkko! I see that you are probably a native Swedish speaker, so your PR can still be useful. I see quite many differences.

**Comment by august-norkko** [comment]
Yeah I am a native speaker, there are some improvements imo. :)

**Comment by august-norkko** [comment]
Any update on this? @alexanderby

**Comment by alexanderby** [comment]
Sorry for the delay, thanks for the update. I will publish it soon. There is something wrong with Chrome Web Store updates reviews, they can take several weeks, so I'm seeking for a way to improve it.

**Comment by alexanderby** [comment]
Hi @august-norkko,

Could you please have a look, if it is possible to shorten some phrases? The problem is in app's design, and I'm working on the improvements, but still unfinished yet.

Screen Shot 2020-01-16 at 11 29 05
Screen Shot 2020-01-16 at 11 30 55

To check how it will look, if you don't want to deal with the source code, please right-click the overflown text, click "Inspect", double-click text between `<span>text</span>` or other element, modify it and press Enter.

**Comment by august-norkko** [comment]
Hey, I will have a look later today.

**Comment by alexanderby** [comment]
I've shortened some phrases, since I'm going to make an update right now https://github.com/darkreader/darkreader/commit/4376bcecafab2ebc49fa2e8a52c3488a1b0231ac

**Comment by august-norkko** [comment]
Ah okay! Yeah it works, one thing is that `@privacy` field could be `Policy` as you suggest.
Thanks for all the work by the way, I love the extension.

**Pull request merged**
