### PR TITLE
Proxy document.styleSheets

### LINKED ISSUE #5009: [Broken Website] pushbullet.com
# Broken Website

## Website
https://www.pushbullet.com/

## How to Reproduce

Have darkreader enabled for all websites.
Go to https://www.pushbullet.com/

## Expected behavior

Website should load normally.

## Actual behavior

Page stays blank.

## System Information

- OS: MacOS
- Browser: Firefox 85.0.1
- Dark Reader Version: 4.9.27

## Additional context

Reactivating DarkReader after the website has loaded works fine.
JS Console logs the message:
```
error message:CSSStyleSheet.insertRule: Not allowed to access cross-origin stylesheet stack:proxyInsertRule@https://www.pushbullet.com/:31:60
onecup.css@https://www.pushbullet.com/js/pushbullet.js:7989:33
@https://www.pushbullet.com/js/pushbullet.js:11890:8
onecup.css@https://www.pushbullet.com/js/pushbullet.js:7982:5
@https://www.pushbullet.com/js/pushbullet.js:11889:6
@https://www.pushbullet.com/js/pushbullet.js:12385:4
 type:unhandled
```

### PR DESCRIPTION
**Pull request by Gusted**
- Remove darkreader's styles from document.styleSheets.
- Add 'dom.iterable' to allow `[...document.styleSheets]`.
- Resolves #5009

### CODE REVIEW

**Comment by Gusted** [comment]
[binaries.zip](https://github.com/darkreader/darkreader/files/5961688/binaries.zip)

**Comment by bossanovaorca** [comment]
any updates on this PR?

**Comment by Gusted** [comment]
> any updates on this PR?

Technically no, just waiting on a Review. However it cannot break a lot and adding some test into this PR to ensure it's behaving correctly. Will give some confidence to merge it without an review.

**Comment by bossanovaorca** [comment]
@Gusted has this changed been released? I'm still seeing the issue unfortunately

**Comment by Gusted** [comment]
> @Gusted has this changed been released? I'm still seeing the issue unfortunately

Nope, latest release doesn't contain this PR.

**Pull request merged**
