### PR TITLE
Fixed legibility in recall box on CarMax.com

### PR DESCRIPTION
**Pull request by mylastsong18**
The white text against the dark yellow background was very hard to read

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @mylastsong18!

Could you give a example link to test this PR on?

Regards,
Gusted

**Comment by mylastsong18** [comment]
Here is [one](https://www.carmax.com/car/18921079). The yellow box is in the right section of the page where it says This car is CarMax certified

**Comment by Gusted** [comment]
What do you think about this

```css
.recall__placeholder,
.vehicle-history__placeholder {
    background-color: ${yellow} !important;
}
#recall .recall__header *,
#recall .recall--link span {
    color: #2a343d !important;
}
#recall svg,
.vehicle-history__placeholder .vehicle-history a svg {
    fill: #053361 !important;
}
#recall a,
.vehicle-history__placeholder .vehicle-history a {
    color: #004487 !important;
}
```
Should look like [this](https://i.imgur.com/OFJ7HlZ.png)

**Comment by mylastsong18** [comment]
That looks good! I’m new to this so I wasn’t sure if I should use variables or not but I like that better

**Comment by Gusted** [comment]
Oh, let's not use variables for this. It's should be a special section because it's certified I don't want to ruin it to make it a dark background. Users should not experience a site diffrently because of Dark reader.

**Pull request merged**
