### PR TITLE
Dynamic theme fixes for AP News

### PR DESCRIPTION
**Pull request by StevenSchifter**
These fixes are for the breaking news banner.

### CODE REVIEW

**Comment by Myshor** [comment]
Can yoiu share some URL where I can look on that banner?

**Comment by StevenSchifter** [comment]
Unfortunately, the breaking news banner is only visible when there is breaking news. I apologize about that. I last saw one [here](https://apnews.com/hub/israel-hamas-war) after Israel struck Iranian military sites. It's not there now though. If you want, I could post "before" and "after" screenshots next time such a banner appears.

**Comment by Myshor** [comment]
That could be nice. I just want to be sure we don't invert some photos or similar things that will look strange INVERTed. 😉

**Comment by Myshor** [comment]
Ok I think I will merge. If there will be some problems with that banner we will fix that ad-hoc. 😉

**Pull request merged**
