### PR TITLE
Add Recommend Website to README.md

### PR DESCRIPTION
**Pull request by Razuuu**
Added because people like me are too lazy to search :)

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @Razuuu!

2 things that bothers me.

1. Recommends, uhm.... Don't like to phrase it that way. Rather, you could use this site.
2. The standard settings are wrong it should be set to ASCII-Characters.

If you have any other site that correctly orders the site list and little bit rephrase the `recommends` I will merge this PR.

Sorry if I sound harsh, not sure how to phrase it.

Regards,
Gusted

**Comment by AndrewDaGuy** [comment]
> not sure how to phrase it

Maybe "Suggested website", perhaps?

**Comment by Gusted** [comment]
> > not sure how to phrase it
> 
> Maybe "Suggested website", perhaps?

The main problem relies, it's third party website that can change any time to include trackers etc. Preferably I setup a simple site that fetch the dark-site.config and has the correct sort function by default.

**Comment by AndrewDaGuy** [comment]
> > > not sure how to phrase it
> > 
> > 
> > Maybe "Suggested website", perhaps?
> 
> The main problem relies, it's third party website that can change any time to include trackers etc. Preferably I setup a simple site that fetch the dark-site.config and has the correct sort function by default.

Sounds better to me than some sketchy website 👍

**Pull request closed without merging**
