### PR TITLE
fix(text-style): use case-insensitive CSS selectors

### PR DESCRIPTION
**Pull request by oberrich**
See also
- https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors
- https://caniuse.com/css-case-insensitive

This PR was previously submitted as #13312 and landed by @Myshor however @Gitoffthelawn has raised concerns about performance so we're asking for review by @alexanderby.

### CODE REVIEW

**Review by alexanderby — COMMENTED** [review]
I really don't know the performance implications of case insensitive selectors. It could be optimal in Chrome, but slow in Firefox or Safari. It's definitely slower, but telling how much slower is hard and requires time to build the test cases and measure the performance. These `*=` selectors are already slow, but there is no easier way to fix the issue. So let's stick to the previous case-sensitive version if it already works. It's fine to have 2 extra code lines if it's faster.

**Comment by oberrich** [comment]
This is micro optimization on n=2 CSS selectors, at the cost of semantical correctness and, as @Myshor pointed out earlier, coverage.

I'm not going to try to please everybody, so I'm fine whether or not this gets merged, but do feel obligate to at least reiterate this point.

**Comment by Gitoffthelawn** [comment]
@alexanderby I agree that we should prioritize performance over 2 short lines of code, especially when a PR is presented that is not fixing any documented issue.

**Comment by oberrich** [comment]
Clearly the maintainers feel it’s best to make the Senior Contributor happy and not listen to any technical arguments instead.
Closing this PR to keep my sanity.

**Comment by alexanderby** [comment]
Please guys stop this argument. It's not worth it. The impact of this change is +0.0001% positive or -0.0001% negative. I mean, maybe there is a website that has `<div class="ICON">` or similar, and maybe someone with Dark Reader's custom font will ever meet it. Or maybe there is a website with a lot of elements like `<div class="abdcefgh_ICO">` and this string search will repeat over and over again for people with custom font settings. Once we have an issue reported we can return to this change.

Everyone has good points and important problems were raised:
1. The impact of Dark Reader's global font overriding the font icons and an enormous amount of different class name variations and the necessity to maintain the list of exceptions.
2. The performance of attribute selectors with a matching string.
3. Premature optimisations.
4. Premature problem solving.
5. The impact of arguments on the internet on mental wellbeing.

I hope everyone learned something new from this argument and will consider it when making future changes and comments.

A few useful articles on CSS selector performance and measurement:
https://blogs.windows.com/msedgedev/2023/01/17/the-truth-about-css-selector-performance/
https://developer.chrome.com/docs/devtools/performance/selector-stats

**Pull request closed without merging**
