### PR TITLE
Remove unused plugin-commonjs

### PR DESCRIPTION
**Pull request by jatin-code777**
`@rollup/plugin-commonjs` is not required. This PR removes it.

### CODE REVIEW

**Comment by Gusted** [comment]
@alexanderby Could you chop in here I remember the switch from gulp to npm scripts when this was introduced however it indeed looks it's not needed. Where I actually tought it was needed for malevic to be injected properly.

**Comment by alexanderby** [comment]
Hi @jatin-code777! Could you please run `npm install`, then run `npm run build` and check if it runs without errors and `build/` folder contains JS and HTML files?

**Comment by jatin-code777** [comment]
Hi, @alexanderby. I had checked this, but I just checked it again and it works without errors. I even `diff`ed the generated build folders before and after making this change and they are the same. `npm run test` also passes.

**Comment by alexanderby** [comment]
Great, thank you.

**Pull request merged**
