### PR TITLE
Fix for microsoft.com

### LINKED ISSUE #6632: [Broken Website] microsoft.com
## Website Address

https://www.microsoft.com/en-us/windows/windows-11?ocid=smc-win-tab

## Expected Behavior

All words in the web page must be white and the background must be black. 

## Actual Behavior

But the words don't turn white and the background has some errors.

When I turn on the extension

image

When I turn off

image

Can you change background of these logo in the end of the site ?

image

## System Information

OS: Windows 11 build 22000.168 64bit
Browser: Edge 92.0.902.78
Dark Reader Version: 4.9.34

### PR DESCRIPTION
**Pull request by Gusted**
- Resolves #6632

### CODE REVIEW

**Comment by NguyenASang** [comment]
It doesn't fix the errors

**Comment by Gusted** [comment]
It's the best we can do. Otherwise send a angry email to microsoft about why they use a full width image as "background" because we cannot go invert the images(which will make their background color dark) as that will mess up the image and kinda defeat the purpose. I've already sent enough angry emails for this week to prepare another one.

**Comment by NguyenASang** [comment]
> It's the best we can do. Otherwise send a angry email to microsoft about why they use a full width image as "background" because we cannot go invert the images(which will make their background color dark) as that will mess up the image and kinda defeat the purpose. I've already sent enough angry emails for this week to prepare another one.

No, you just need to change the color of words from white to black. You don't need to to change the color of the background's picture. 

And remove this when turn on the extension:

image

When I turn off:

image

**Comment by NguyenASang** [comment]
I apologize for my stupid request to change the background to dark.

**Comment by Gusted** [comment]
image
image


The current color in contrast looks more or less the same as the darker color. Given the now more "darkened" image.

**Comment by NguyenASang** [comment]
Can you reset the color of the picture and only change the color of text 🙂

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/pull/6638

**Pull request merged**
