### PR TITLE
fix dark theme for joyreactor.cc

### PR DESCRIPTION
**Pull request by senid231**
image

image

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @senid231!

What problem does this PR solves?

Regards,
Gusted

**Comment by senid231** [comment]
hi @Gusted,

it fixes dark reader for site http://joyreactor.cc/

currently it have orange background and orange buttons with light grey text on it. I've just improve dark styles for it.

here's how it looks with default dark reader styles

image

**Comment by Gusted** [comment]
Hi @senid231!

In my eyes it doesn't seems to fix anything, it seems to be some cosmetic changes.

Regards,
Gusted

**Comment by senid231** [comment]
Thanks for answer @Gusted .

My change replaces bright orange background with default dark backround color.
Also it change buttons with bright orange background and grey text with transparent background, dark orange border and text color.

Could you please explain how you distinguish "some cosmetic changes" from changes that fixes dark theme or improves it's readability?

Regards,
senid231

**Comment by Gusted** [comment]
Hi @senid231!

The current fixes are changing the colors and background-colors to a better native color of the original to improve the contrast or simply giving the correct color as Dark Reader wasn't styling it at all. However in this PR the background-color is being changed to a dark-ish color which don't seem to increase readability over the other elements, nor seems removing the background-color of the nav elements.

Regards,
Gusted

**Comment by Gusted** [comment]
After another look I think the body's background can be changed to improve readability to other elements, however I still don't think changing the nav menu is a good idea.

Regards,
Gusted

**Pull request closed without merging**
