### PR TITLE
Optimize and fix for www.baidu.com

### PR DESCRIPTION
**Pull request by Yersmagit**
Optimize and fix for www.baidu.com

### CODE REVIEW

**Comment by Yersmagit** [comment]
||Berore|After|
|-|-|-|
|1|image|image|
|2|image|image|

**Comment by Myshor** [comment]
As I can see you use static colors in fixes but it breaks light scheming in Dark Reader.

For example: https://www.baidu.com/s?wd=%E5%BA%86%E7%A5%9D%E4%BA%BA%E6%B0%91%E6%94%BF%E5%8D%8F%E6%88%90%E7%AB%8B75%E5%91%A8%E5%B9%B4%E5%A4%A7%E4%BC%9A&sa=fyb_n_homepage&rsv_dl=fyb_n_homepage&from=super&cl=3&tn=baidutop10&fr=top1000&rsv_idx=2&hisfilter=1

obraz

To fix this you should use ${color} where the color is the original color to invert(100%) and hue-rotate(180deg).

So example how to use this... Let's pretend you use some color now like #334455 instead if you want to have same effect you use ${#AABBCC}

So you make negative and change sides for RED and BLUE.

**Review by Myshor — CHANGES_REQUESTED** [review]
Need to fix colors to work fine with light and dark scheming.

**Review by Yersmagit — COMMENTED** [review]
**Update 24/09/21 18:30(UTC+8) :** Fix colors to work fine with light and dark scheming.

image

**Comment by Yersmagit** [comment]
**Update 24/09/21 23:10(UTC+8) :** Fix bugs.

**Review by Myshor — APPROVED** [review]

**Pull request merged**
