### PR TITLE
Update dynamic-theme-fixes.config - fix black logo

### PR DESCRIPTION
**Pull request by 8times9**
Before:
image

After: 
image

### CODE REVIEW

**Comment by 8times9** [comment]
I see my pull request failed to pass the test, I'm not sure how this change could have caused it to fail though?

**Review by AndrewDaGuy — APPROVED** [review]
LGTM, Andrew Approved :+1:

> I see my pull request failed to pass the test, I'm not sure how this change could have caused it to fail though?

Eh, that's normal

**Comment by Gusted** [comment]
> LGTM, Andrew Approved +1

Approved is for PR's that are ready to merged and passes the checks. ;)

**Review by Gusted — APPROVED** [review]
+1 I just had to move the site under `dash.[...]` so it would be in alphabetic order.

**Pull request merged**
