### PR TITLE
Update dynamic-theme-fixes.config

### PR DESCRIPTION
**Pull request by dgutkowsky**
quick fix for the modal window and wildlings image in thronemaster.net website.
after the fix the rest is perfect  (both dark and light theme)

### CODE REVIEW

**Comment by Gusted** [comment]
Where can I find the elements?

**Comment by dgutkowsky** [comment]
you need to be logged in to check it out.
I have tested it , it works quite good.

**Comment by Gusted** [comment]
I didn't watched Game Of Thrones
!{](https://i.imgur.com/fJJXCrm.png) Could you help me out here?

**Comment by dgutkowsky** [comment]
3

just check this out - will be easier for you

https://game.thronemaster.net/?game=239363

**Pull request merged**
