### PR TITLE
Added danish translation to the locale list

### PR DESCRIPTION
**Pull request by MikaelFangel**
### Changes
 - Adds a danish translation to the locales

### CODE REVIEW

**Comment by MikaelFangel** [comment]
I'm not quite sure what the failed check means and how to resolve it. 😓 😳

**Comment by alexanderby** [comment]
Hi @MikaelFangel, thank you for the translation! We are adding some new options to the app, I google translated them, please check if possible (see `#==== Toggle menus ====`).

**Comment by alexanderby** [comment]
Feel free to open another PR with the edits. We will be submitting another update on Sunday-Monday.

**Comment by MikaelFangel** [comment]
Thanks! I'll look through the other translations tomorrow (:

**Comment by MikaelFangel** [comment]
@alexanderby - I only found a small mistake and have created the pr #11083 with the correction.

**Pull request merged**
