### PR TITLE
Fix for yelp.com

### PR DESCRIPTION
**Pull request by c-nagy**

### CODE REVIEW

**Review by Gusted — CHANGES_REQUESTED** [review]
Not sure which are targgeted for the input, but it should be removed. I'm not sure why it should white?

**Comment by c-nagy** [comment]
> Not sure which are targgeted for the input, but it should be removed. I'm not sure why it should white?

It's targeting the search bar on the home page and the results page, just to make it stand out a bit more.

**Comment by Gusted** [comment]
> just to make it stand out a bit more.

Why should it stand more out?. In my eyes that would be a opinionated fix.

**Comment by c-nagy** [comment]
> > just to make it stand out a bit more.
> 
> Why should it stand more out?. In my eyes that would be a opinionated fix.

I guess that's true. Alright, I reverted that part and just left the inversion for the Yelp logo and embedded google map section.

**Review by Gusted — APPROVED** [review]

**Pull request merged**
