### PR TITLE
Add Support for IFrames injecting in API

### LINKED ISSUE #5082: [Question] How to apply dark mode to all iFrames when using DarkReader API in React Project?
# Question

Is there a way to apply dark mode to all iFrames in a page when using API (When using Extension, all iFrame in a page are also rendered in Dark Mode).

## Is your feature request related to a problem? Please describe
If this is not possible currently when using as API, can we get it added?

## Describe the solution you'd like
When using enable, disable methods from API, iframes in a page must be identified and applied with dark mode as it happens when using Extension. I understand Extension uses Extension API to do this. Is it possible to do something similar for API ?

### PR DESCRIPTION
**Pull request by Gusted**
- Enables the scenario where an application have IFrames and can trough proper configuration be styled trough Dark Reader.
- Uses user's defined callback to inject a copy of darkreader.js, so it can be either an local copy or injecting the textContent or hence any other method.
- Uses CustomEvents to talk to other darkreader.js to update/create/remove dark reader.
- Key implemention to #5063 
- Resolves #5082

### CODE REVIEW

**Comment by Gusted** [comment]
[scenarios.zip](https://github.com/darkreader/darkreader/files/6005329/scenarios.zip)
[darkreader-api.zip](https://github.com/darkreader/darkreader/files/6005332/darkreader-api.zip)

**Comment by Tzurz** [comment]
This is amazing! Any chance this could be merged soon? It would help me very much.
If there's something I can do to help, please let me know :)

**Comment by rafaelmaeuer** [comment]
Hey @Gusted really nice work. I wanted to use your version to display a dark version of a web page e.g. http://isittimeforabeer.com which works fine with darkreader browser-extension. But using one of your example scenarios the page stays light although a `isdarkreaderactived="1"` is added to the iframe element...

Any ideas?

**Comment by Gusted** [comment]
@rafaelmaeuer 🤷🏽 current PR is slippery slope

**Comment by rafaelmaeuer** [comment]
Could you nevertheless provide a compiled version of your latest update? Or is it easy to create one myself? I am really looking for a solution of rendering dark version of webpages with some kind of proxy/darkreader step in between.

**Comment by 1979044994** [comment]
Has the program been abandoned? Will you consider solving this problem in the future?

**Pull request closed without merging**
