### PR TITLE
Fix for whatsapp.com

### PR DESCRIPTION
**Pull request by Gusted**
- Try to restore the QR as much as possible (likely increase stability to scan this QR code?)
- Attempt to fix the issue #9659

### CODE REVIEW

**Comment by ShalokShalom** [comment]
Thanks a lot, that sounds great!

I will immediately test with all my devices, once I can.

**Comment by ShalokShalom** [comment]
I guess this will take a while, until a new version comes out. 

Is there any way, how I cam get there early? :)

**Comment by Gusted** [comment]
I will merge it for now, so you can use [the synchronization feature](https://github.com/darkreader/darkreader#site-fixes) to fetch the latest fixes.

**Comment by ShalokShalom** [comment]
Thanks 😊 

 Did you consider Fosshost as CDN?

https://fosshost.org/

**Comment by ShalokShalom** [comment]
Wonderful, that fixes that!

I have tried it with just one mobile, and I am confident it works now

Might have been related to the API that you and I were using

I had an Android 10, maybe you are using iOS devices and they are better to read QR codes

thanks a ton :D

**Comment by Gusted** [comment]
> Did you consider Fosshost as CDN?
> 
> https://fosshost.org/

No the syncronization was rather a "hack"/"workaround" for those that needed fixes before a new Dark Reader release. But I'll happily look into other options to make it more modernized.

**Pull request merged**
