### PR TITLE
Edited whitelist

### PR DESCRIPTION
**Pull request by alazymeme**
Added supinic.com
Removed streamlabs.com
Added streamlabs.com/dashboard

Not sure if the streamlabs way is the best way of doing it, but I'd rather not be blinded by their homepage.

### CODE REVIEW

**Comment by Gusted** [comment]
But their dashboard has a native not by default dark theme. I don't think everyone wants their native because its material dark but rather use darkreader

**Comment by alazymeme** [comment]
@Gusted Last I checked, it is a dark green by default. Has this changed?

**Comment by Gusted** [comment]
I just logged into a fresh account on a private window

**Comment by alazymeme** [comment]
@Gusted Thank you for pointing that out. Not sure why any dev would revert dark mode by default, but whatever I guess.

**Comment by Gusted** [comment]
https://github.com/darkreader/darkreader/wiki/Merging-Pull-Requests Rule 4. Make the 2 seprates Pull request for this. Can't merge this.

**Comment by alazymeme** [comment]
Nah, I'm not making another pull request; that's just stupid that it would be closed.

**Comment by Gusted** [comment]
Can't reopen it anymore lemme make 2 separate pull requests than. Thank you for contributing!

**Pull request closed without merging**
