### PR TITLE
Fix for leetcode.com

### LINKED ISSUE #3535: [BUG] Leetcode problems don't appear in dark mode
### **Describe the bug**

Leetcode.com works fine, but going to the problem itself doesn't most of the time, showing a dark screen instead of the darkmode text. 

### **Steps to reproduce**

- Go to Leetcode.com
- Click on a problem

### **Expected behavior**
- expect theme to be dynamically changed to a dark mode

### **Actual behavior**

- theme only occasionally changes to dark mode, no idea why 

### **Screenshots**

https://drive.google.com/file/d/1mHBifLyJRPVQPInGeBk74FvYMOvEnW9U/view?usp=sharing

### **System Information:**
 - OS: Windows 10
 - Browser: Chrome
 - Dark Reader version: 4.9.16

### **Additional context**

It happens randomly, don't know why. Will occasionally work, but most times just shows a black screen. 

PS: Love this extension!!! Fantastic work, thank you so much for building it

### PR DESCRIPTION
**Pull request by mxiao6**
- Resolves #3535

### CODE REVIEW

**Comment by Gusted** [comment]
Example URL?

**Comment by mxiao6** [comment]
> Example URL?

The whole page is masked by black background: https://leetcode.com/problems/two-sum/

**Comment by Gusted** [comment]
I honestly don't see a change.

**Comment by Gusted** [comment]
It does not even have a specific background-color

**Comment by mxiao6** [comment]
> It does not even have a specific background-color ![](https://camo.githubusercontent.com/0e86a71183bc2214fd9ee0e4ec8ccf13533136e4/68747470733a2f2f692e696d6775

@Gusted  I'm using Dynamic Theme generation mode. Its background-color is inherited from body, which has a black background-color added by darkreader.

**Comment by Gusted** [comment]
Woops I see.

**Pull request merged**
