### PR TITLE
Add dark site react-spectrum.adobe.com

### PR DESCRIPTION
**Pull request by BANOnotIT**

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @BANOnotIT,

Thank you for your PR, however this is not a dark-by-default site:
image

**Comment by BANOnotIT** [comment]
How do you define "dark by default"? For me it's dark when I open it. I guess it's because they use prefer-color-scheme: dark. Might be your browser doesn't use it?

**Comment by Gusted** [comment]
See [the criteria](https://github.com/darkreader/darkreader/blob/main/CONTRIBUTING.md#adding-a-website-that-is-already-dark) for the list. That defines it.

**Comment by KaKi87** [comment]
@BANOnotIT Added to my [Dark Reader dynamic blacklist](https://git.kaki87.net/KaKi87/userscripts/src/branch/master/darkReaderDynamicBlacklist/README.md) userscript in the *System or user (binary)* category.

**Pull request closed without merging**
