### PR TITLE
yagpdb.xyz

### PR DESCRIPTION
**Pull request by Gusted**
Adds the main domain to the dark site list but the subdomain `docs.` not to it
#2055 for more info
main domain

subdomain docs.yagpdb.xyz

### CODE REVIEW

**Comment by alexanderby** [comment]
Sorry, this is not yet possible. It is planned to add [negative patterns](https://github.com/darkreader/darkreader/issues/373), so it will look like:
```
website.com
!docs.website.com
```
This is is intended to be simple. Going further, it is planned to add a website's own dark mode auto-detection.

**Comment by Gusted** [comment]
So I should wait until the new URL match patterns? And then change it to !docs.yagpdb.xyz

**Comment by alexanderby** [comment]
Yes, let's wait. Also it is planned to add auto dark mode detection, so maybe this list will become unnecessary.

**Comment by Gusted** [comment]
#2327

**Pull request closed without merging**
