### PR TITLE
Fix for boardgamearena.com

### PR DESCRIPTION
**Pull request by branflaker**
Added boardgamearean.com section to dynamic-theme-fixes.config.
Updated card text to be darker against light card background for Memoir 44 game.

### CODE REVIEW

**Comment by branflaker** [comment]
@bershanskiy Why add the wildcard?  I don't see that used for other domains in the config.

**Comment by bershanskiy** [comment]
@branflaker Eventually, we plan to migrate away from the current behavior of treating `example.com` like a wildcard meaning "`example.com` and all its subdomains". But this is some time off.

**Comment by bershanskiy** [comment]
Other than that, I think it's fine. I can merge whenever it is convenient for you.

**Comment by branflaker** [comment]
Okay, thank you -- I just noticed that it failed the alphabetical sorting check because of that and so when I inspected for other instances of using a wildcard, I didn't see any.

Happy for it to merge whenever.  There may be more changes with this site/domain in the future because there's a lot of custom CSS for each game on the site.

**Pull request merged**
