### PR TITLE
Straigten Dark Reader ASCII art

### PR DESCRIPTION
**Pull request by WebMechanic**
The ASCII art seemed a bit shakey

### CODE REVIEW

**Review by Gusted — COMMENTED** [review]
Thanks for the PR,

but could you explain why this needs to be changed? The current result looks fine to me.
It doesn't seem to be that shaky.
image

**Comment by WebMechanic** [comment]
Then there must be two copies of this precious work of art, 'cos the one I saw (and changed) has "doubled" 3d-ish lines and looks a bit different from your screenshot -- which also looks fine to me :)

Have a look at the diff and you shall see :-)

**Comment by Gusted** [comment]
Are you referring to how the ASCII looks in the code? 
That's normal, I only care about the output, which is on the console. We have to use escape character, but in the output those escape characters are removed.

**Comment by WebMechanic** [comment]
oh, gosh ... right! should've thought of that 🤦‍♂️ 

my bad, sorry for bothering :)
Now, how do I withdraw a PR? 🤔 do I just close this and delete my branch?

**Comment by Gusted** [comment]
> oh, gosh ... right! should've thought of that man_facepalming
> 
> my bad, sorry for bothering :)

No worries 😄, everyone could make that same thought.

**Pull request closed without merging**
