### PR TITLE
Fix for techdirt.com

### PR DESCRIPTION
**Pull request by neonr4in**
CSS fix for techdirt.com

https://www.techdirt.com/

### CODE REVIEW

**Review by Gusted — COMMENTED** [review]
What's this supposed to fix?

Without any fixes this site looks good.

**Comment by neonr4in** [comment]
Does it? It looks like this for me (already tried on multiple profiles with default configuration, all with same results)

techdirt_no_fix

As for the fix, it should look like this

techdirt_with_fix

**Comment by Gusted** [comment]
This is without any of the fixes:
image

If there's something wrong on your side it should be turned into a bug report, on both firefox and chromium they look like they should without any additional fixes.

**Comment by neonr4in** [comment]
All right, something went awry on my end and now it is fixed

Sorry for wasting your time

**Pull request closed without merging**
