### PR TITLE
Improve quality of issue templates

### PR DESCRIPTION
**Pull request by Gusted**
- Add an warning that an issue can be closed if it don't have an issue template.
- Add an warning that the issue can be closed if it doesn't fill out basic information.
- Add descriptions.
- Default messages into comments.

Description:
Hopefully people will actually follow this else the issue can be closed without any notice, which will hopefully improve the quality in reported issues.

### CODE REVIEW

**Comment by Gusted** [comment]
Hey @Yash-Singh1!

Would you like to run an Markdown linter on those files?

Regards,
Gusted

**Comment by Yash-Singh1** [comment]
@Gusted Here is the link to the node markdownlint demo: https://dlaa.me/markdownlint/

**Comment by Gusted** [comment]
> @Gusted Here is the link to the node markdownlint demo: https://dlaa.me/markdownlint/

Thanks!

**Comment by Rakleed** [comment]
@Gusted Why leave _[Broken Website]_, _[BUG]_, _[Feature Request]_ in the title when you add a label with the same name to the issue?

And it seems to me that the example of 'Steps to reproduce' should also be fully commented out.

And why is 'Dark Reader' spelled as 'Darkreader'? On the site and in stores, it is still written as Dark Reader.

**Comment by Gusted** [comment]
> @Gusted Why you leave _[Broken Website]_, _[BUG]_, _[Feature Request]_ in the title when you add a label with the same name to the issue?

1. Personal workflow, in notifications you will only see the title + description. It's easier to filter out certain things when I have a bunch of emails.
2. Overall indication of what kind of issue it is, the labels can actually be redundant and planned to be removed as it doesn't add an extra value, other then filtering types of issues in Github.

> And it seems to me that the example of 'Steps to reproduce' should also be fully commented out. 

Not sure how I've missed that.



> And why is 'Dark Reader' spelled as 'Darkreader'? On the site and in stores, it is still written as Dark Reader.

I've a mixed variation on how to type Dark Reader, just a personal thing, will be changed.

**Review by alexanderby — APPROVED** [review]

**Pull request merged**
