### PR TITLE
Upwork darkmode changes (fixed many issues)

### PR DESCRIPTION
**Pull request by Mirm0n**
Dark reader did not change Upwork.com into dark mode correctly. There were some minor issues
Here are the fixes I've made:
1-Remove white gradient highlights on the tags sections for each job post.
2-The green button on the right had a white drop shadow and I removed it.
3-in the messages tab, the skeleton loading is white and not dark, so it looks horrible, I changed it to the dark reader skeleton color.

Try it out if you work on upwork (or not, but you need to make a freelance account to try this) and tell me what you think!

Untitled-1

### CODE REVIEW

**Comment by Mirm0n** [comment]
Changed this too

before-after-contrast-change

**Comment by Gusted** [comment]
Please de-remove the other fixes.

**Comment by Mirm0n** [comment]
> Please de-remove the other fixes.

Sorry, I'm new to the whole GitHub thing. Wwhat do you mean by de-remove? and what "other fixes" are you refereeing to?

**Comment by Gusted** [comment]
In this PR you've also "removed" other Site's fixes:

image

Please revert these changes so that within your PR they are there.

**Comment by Mirm0n** [comment]
> In this PR you've also "removed" other Site's fixes:
> 
> image
> 
> Please revert these changes so that within your PR they are there.

I added a new commit, did I do it correctly?

**Comment by Mirm0n** [comment]
I added a new commit, did I do it correctly?

**Comment by Gusted** [comment]
> I added a new commit, did I do it correctly?

I think it's better if you open a new PR which include the changes, because this PR now add existing content which is already on the master branch.

**Comment by Mirm0n** [comment]
> > I added a new commit, did I do it correctly?
> 
> I think it's better if you open a new PR which include the changes, because this PR now add existing content which is already on the master branch.

Ok great I'll do that but I found some other issues on the website, so I'll fix them today (probably) and make one PR instead of making another one later with that fix. Thank you!

**Comment by Gusted** [comment]
Thank you for contributing!

**Comment by Mirm0n** [comment]
It's my pleasure <3 love the extension

**Comment by kizule** [comment]
New version of Upwork interface got released, I think that this pull request should be updated to reflect new interface changes.
Right now it looks very bad for me.

image

**Pull request closed without merging**
