### PR TITLE
Update dark-sites.config

### PR DESCRIPTION
**Pull request by PyroGenesis**
sqldbm.com is already dark themed

image
image

### CODE REVIEW

**Comment by Gusted** [comment]
Hmm, the home page does seem like to contain some light thingies.... But if everything after the login is dark(by default) then I will merge it, as this will be the as we do with netflix.

**Comment by PyroGenesis** [comment]
Good point. I made an account to test it.

After login, the project dashboard is light-themed
image

But creating / editing a project is always dark-themed
image

Should I change the URL to app.sqldbm.com?

**Comment by Gusted** [comment]
Is the project dashboard within `app.`?

**Comment by PyroGenesis** [comment]
No, the light-themed project dashboard is only `sqldbm.com` while the dark-themed project page is `app.sqldbm.com`

**Comment by Gusted** [comment]
Sure thing then, change it to `app.`  Make sure to update the line position of the site entry.

**Comment by PyroGenesis** [comment]
It's done

**Review by Gusted — APPROVED** [review]

**Pull request merged**
