### PR TITLE
Create fa-IR.config

### PR DESCRIPTION
**Pull request by Matin-A**
Hi, this is translation to Farsi/Persian (Iran).
I believe there might be some visual issues since Farsi is Right to Left, 
so contact me if there were any issues.

### CODE REVIEW

**Comment by alexanderby** [comment]
Hi @Matin-A! Maybe it makes sense to rename file to `fa.config`? I see that Chrome supports `fa` locale https://developer.chrome.com/webstore/i18n

Could you please right-click Dark Reader icon, click "Inspect Popup". Switch to "Console" tab and execute:
`chrome.i18n.getUILanguage()`
then `navigator.language`
and then `navigator.languages`

Please share the results of all 3 commands.

**Comment by alexanderby** [comment]
Well @Matin-A, it seems you are not available. I will merge it and add `fa` file as a copy of this.

**Comment by Matin-A** [comment]
I'm terribly sorry for not responding, I wasn't active on GitHub since then. Do i supposed to delete this branch?

**Comment by alexanderby** [comment]
Hi, don't worry, I've copied your translation to `fa.config` and left `fa-IR.config` too. It is similar situation as for `en`, `en-US` and `en-UK`. Now it works https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=fa

**Pull request merged**
