### PR TITLE
Remove backround of Thunderbird header tables

### LINKED ISSUE #9118: [Broken Website] imap: on thunderbird with attached email
# Broken Website Report

## Website Address

imap:

## Steps To Reproduce

Send yourself an email with another email added as an attachment, and read it in Thunderbird. 

## Problematic Observation

Mailing lists powered by Mailman send emails from members as attached emails if the sender's domain cannot be spoofed because DMARC is enforced on the sender's domain. Thunderbird will render the attached email inline, which is very nice. Unfortunately when Dark Reader is enabled, the inline message header information turns to nearly-white on white.

## Screenshots

image

image

## System Information

- OS: Windows
- Browser: Thunderbird 91
- Dark Reader Version: 4.9.39

### PR DESCRIPTION
**Pull request by seanthegeek**
Fixes #9118

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @seanthegeek!

Have you confirmed that the fixes works? I haven't used thunderbird in a long time and remembered it didn't play with with URLS/Dark Reader matching URL.

**Comment by seanthegeek** [comment]
Yep. I tested it live using the Dark Reader dev tools.

**Review by Gusted — APPROVED** [review]

**Comment by Gusted** [comment]
Thanks!

**Comment by seanthegeek** [comment]
Crap, that should be pop3:

**Comment by seanthegeek** [comment]
Typo fixed. I don't know who uses POP3 nowadays, but now their emails will be dark too. 😅

**Comment by seanthegeek** [comment]
Out of curiosity, how often are these changes include in a new Dark Reader release?

**Comment by Gusted** [comment]
> Out of curiosity, how often are these changes include in a new Dark Reader release?

Currently we're targeting once a month, but fixes can be remotely synced, https://github.com/darkreader/darkreader#site-fixes

**Pull request merged**
