### PR TITLE
Fix for service-now.com

### PR DESCRIPTION
**Pull request by sKravciv**
Fix for code editor in service-now instances
================================

*.service-now.com

CSS
.cm-s-snc span.cm-string {
  color: #cf947b !important;
}
.cm-s-snc span.cm-def {
  color: #60a4d8 !important;
}
.cm-s-snc span.cm-property {
  color: #ffffff !important;
}
.cm-s-snc_readonly span.cm-string{
  color: #cf947b !important;
}

### CODE REVIEW

**Comment by bershanskiy** [comment]
Hi @sKravciv, how may I access this editor to test the fix? Thanks.

**Comment by bershanskiy** [comment]
And the CI might fail, I think.

**Comment by sKravciv** [comment]
Hi @bershanskiy, you cannot access instance of servicenow because it is enterprise solution. You can request developer instance [here](https://developer.servicenow.com/dev.do#!/home) - but it is a little bit complicated. I can provide screeshots if that would be helpful. What can I do to make the CI pass? Thanks

**Comment by bershanskiy** [comment]
My main concern is the arbitrary color values like `#cf947b`. They might not play well with custom color settings.

**Comment by sKravciv** [comment]
I was using colors from different servicenow editor where the code is readable
screen

**Comment by bershanskiy** [comment]
Would it be possible to use Dark Reader CSS variables like these?
```CSS
--darkreader-neutral-background
--darkreader-neutral-text
--darkreader-selection-background
--darkreader-selection-text
```

**Comment by sKravciv** [comment]
Unfortunately no. I have tried using all of them but it makes the code unreadable

**Comment by sKravciv** [comment]
Hi @bershanskiy, is it possible to merge this with base branch or is there something missing? Thank You

**Pull request merged**
