### PR TITLE
Retry in x seconds

### LINKED ISSUE #3001: [Broken Website] The Rust Programming Language Book
**Website**
https://doc.rust-lang.org/book/

**How to Reproduce**
Visit the site

**Expected behavior**
image

**Actual behavior**
image

**System info:**
 - OS: macOS 10.14.6
 - Browser: Google Chrome 83.0.4103.97 (Official Build) (64-bit)
 - Darkreader Version: 4.9.13

### PR DESCRIPTION
**Pull request by Gusted**
- Resolves #3001
- Resolves more for sure

### CODE REVIEW

**Comment by LoganDark** [comment]
Any way to use a shorter interval? 2 seconds is a very long time, I can double-tap my keybind way faster than that

**Comment by Gusted** [comment]
I litterly didn't notice any difference of the 2 second @LoganDark I can send a compiled copy so you can see yourself.

**Comment by LoganDark** [comment]
I can load webpages in under a second so 2 seconds would definitely be noticeable for me... is there any other way?

**Comment by Gusted** [comment]
[debug.zip](https://github.com/darkreader/darkreader/files/4866572/debug.zip)
Test it out please and come back

**Comment by LoganDark** [comment]
Weird, it seems instant. That's not 2 seconds at all. Ok, I think this is fine.

**Comment by Gusted** [comment]
Yeah I know, I was surprised too! An average laptop shouldn't notice it so it should be a fine else we just lower it a bit.

**Comment by LoganDark** [comment]
Well, mine is not average at all and I don't ever see any white on the page. :P

**Comment by Gusted** [comment]
I noticed that :P But it does the trick somehow so It's fine

**Pull request merged**
