### PR TITLE
Global Dark Sites: Added a few Apple news websites

### PR DESCRIPTION
**Pull request by lemeb**
A few Apple news sites that have been making the switch after the release of iOS 13.

### CODE REVIEW

**Comment by alexanderby** [comment]
Hi. These sites support native dark mode, but are not dark by default when system Light appearance is selected. Well, things got complex, I have to think about the purpose of this list, it is becoming useless. Maybe the option is needed to detect native dark mode support and prevent doing anything.

**Comment by lemeb** [comment]
I think that's right, especially since some of the sites that are _currently_ in the list (like the Docker Docs) are not dark by default but offer the option...

I think it might be wise to create two lists:
- `dark_sites.config`: websites that are dark by default anywhere
- `prefers_color_scheme_sites.config`: websites that are dark if the browser communicates a dark mode, which is the case of these websites, [Bugzilla](https://hacks.mozilla.org/2019/05/firefox-67-dark-mode-css-webrender/), the Docker docs, etc. That's where — to take an example — macstories.net would lie.

Let's imagine a case where the user has Dark Reader turned ON globally, "use system color scheme" OFF, and wants to visit, say, macstories.net:
- If the system color scheme sent by the browser `== 'dark'`: don't use `prefers_color_scheme_sites.config`, since macstories.net already knows that the user prefers a dark website.
 - If the system color scheme sent by the browser is `!= 'dark'`: use `prefers_color_scheme_sites.config`. Instead of generating a dark CSS, Dark Reader injects `prefers-color-scheme: dark`, as proposed in #1285, and let macstories.net render its native theme.

I have to mention that I'm on Firefox on Catalina with Dark Mode enabled, and that Firefox is _not_ passing along that I'm on Dark Mode:
- With Chrome and Safari macstories.net is natively dark, 
- But with Firefox, is natively light with Dark Reader "OFF" and artificially dark with Dark Reader "ON".

**Comment by FranklinYu** [comment]
Bugzilla implemented it in a simple way, but Docker docs site seems to have a UI switch for users to override this settings.

> * If the system color scheme sent by the browser `== 'dark'`:
> 
>     * don't use `prefers_color_scheme_sites.config`, since macstories.net already knows that the user prefers a dark website.

By "don't use it" did you mean "treat it the same as `dark-sites.config`"?

**Comment by lemeb** [comment]
> By "don't use it" did you mean "treat it the same as `dark-sites.config`"?

Yep! When the user goes on the website, it is dark by default, so our job is done here to a degree. If the user prefers to activate light mode on the website in question, well, free to them!

**Pull request closed without merging**
