### PR TITLE
Add kika.de

### PR DESCRIPTION
**Pull request by Myzel394**
This site seems to be completely dark. There are some white buttons, but in overall it's pretty dark

### CODE REVIEW

**Comment by bershanskiy** [comment]
Hi, thanks for this PR, but it appears that only the landing page supports dark mode well. The rest of the site is mostly light, for example:
https://www.kika.de/erwachsene/index.html

**Comment by Myzel394** [comment]
sorry about that. I'll create a PR instead to fix the small issues on the kids section. @bershanskiy do you know how to exclude Dark Reader on specific elements?

**Comment by bershanskiy** [comment]
@Myzel394 We have some documentation explaining how to use Dark Reader Developer Tools [here](https://github.com/darkreader/darkreader/blob/main/CONTRIBUTING.md). You can use them right from your browser without building Dark Reader yourself. Also, if you would provide a list of broken elements (preferably with screenshots) I would be able to look into this as well.

**Comment by Myzel394** [comment]
@bershanskiy on kika.de we can simply exclude the whole "nav" element and its children.

Navbar with DarkReader (incorrect)
image

Navbar without DarkReader (correct)
image

**Comment by Myzel394** [comment]
The selector is:

```
nav[data-testid="navbar"]
```

**Pull request closed without merging**
