### PR TITLE
fix embedded code and table header color for developers.google.com

### PR DESCRIPTION
**Pull request by isaec**
fix colors for embedded code.

before:
image
after:
image

### CODE REVIEW

**Comment by isaec** [comment]
It would also be really nice to be able to set `pref_dark-code` to `1` in local storage so that code blocks are dark without any interaction, but unclear how that could be done - maybe a feature request?

**Comment by isaec** [comment]
Oh my bad, this is basically a duplicate of #5554. One could argue this pr is better, because it does not alter the full line code embeds, but on the other hand #5554 makes the full line code embeds mostly dark with no interaction. Not sure which is really better.

**Comment by FadeMind** [comment]
@isaec I can revert changes in my PR for `developers.google.com` if @Gusted wish. I made fixes for one more site in my PR. Waiting for feedback. Regards

**Comment by Gusted** [comment]
> @isaec I can revert changes in my PR for `developers.google.com` if @Gusted wish. I made fixes for one more site in my PR. Waiting for feedback. Regards

Already merged that PR.

**Comment by Gusted** [comment]
Seems like 

> but on the other hand #5554 makes the full line code embeds mostly dark with no interaction.

I don't see the difference between this PR and the other one.

**Pull request closed without merging**
